// Bancos listos para usar. El docente los agrega a «Mis bancos» con un toque y
// después los puede editar como cualquier otro.
//
// Revisá números de ley y artículos antes de usarlos: están escritos para
// secundaria de la provincia de Buenos Aires, pero conviene chequearlos con tu planificación.

import { GENERALES } from './plantillas-generales.js';
import { MATERIAS } from './plantillas-materias.js';

const t = (termino, definicion) => ({ tipo: 'termino', termino, definicion });
const p = (pregunta, correcta, ...incorrectas) => ({ tipo: 'pregunta', pregunta, correcta, incorrectas });
const par = (a, b) => ({ tipo: 'par', a, b });
const enc = (pregunta, ...respuestas) => ({
  tipo: 'encuesta', pregunta,
  respuestas: respuestas.map((r) => { const [texto, pts] = r.split('='); return { texto: texto.trim(), puntos: Number(pts) }; }),
});

export const PLANTILLAS = [
  {
    id: 'cc-derechos',
    titulo: 'Derechos y participación', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      t('adolescencia', 'Etapa de la vida entre la niñez y la adultez, en la que se consolidan la identidad y la autonomía'),
      t('asamblea', 'Reunión en la que un grupo delibera y toma decisiones en conjunto'),
      t('bien común', 'Lo que beneficia a todas las personas de una comunidad y no solo a algunas'),
      t('centro de estudiantes', 'Organización elegida por voto que representa a los alumnos de una escuela'),
      t('ciudadanía', 'Condición de quien forma parte de una comunidad política y ejerce en ella derechos y obligaciones'),
      t('Convención sobre los Derechos del Niño / CDN', 'Tratado internacional de 1989 que reconoce a niñas, niños y adolescentes como sujetos de derecho'),
      t('delegado / delegada', 'Estudiante elegido por su curso para representarlo'),
      t('discriminación', 'Trato desigual o excluyente hacia una persona por su origen, género, religión u otra condición'),
      t('estereotipo', 'Imagen simplificada y generalizada que se atribuye a todo un grupo de personas'),
      t('identidad', 'Conjunto de rasgos que hacen que una persona sea quien es y se reconozca como tal'),
      t('igualdad', 'Principio según el cual todas las personas tienen los mismos derechos'),
      t('interés superior del niño', 'Principio que obliga a priorizar el bienestar de niñas, niños y adolescentes en toda decisión que los afecte'),
      t('ley', 'Norma general y obligatoria dictada por el Poder Legislativo'),
      t('mediación', 'Forma de resolver un conflicto con ayuda de una tercera persona neutral'),
      t('norma', 'Regla que indica cómo se debe actuar en una comunidad'),
      t('participación', 'Tomar parte activa en las decisiones y los asuntos de una comunidad'),
      t('prejuicio', 'Opinión, generalmente negativa, que se forma sin conocer a la persona o la situación'),
      t('responsabilidad', 'Capacidad de responder por los propios actos y sus consecuencias'),
      t('sujeto de derecho', 'Persona a la que la ley le reconoce derechos y la posibilidad de exigirlos'),
      t('tolerancia', 'Respeto por las ideas y prácticas de los demás aunque sean distintas de las propias'),
      t('voto', 'Forma de expresar una elección en una votación'),
      p('¿Qué tratado reconoce a niñas, niños y adolescentes como sujetos de derecho?', 'la Convención sobre los Derechos del Niño', 'la Constitución de 1853', 'el Acta de la Independencia', 'el Código Penal'),
      p('¿En qué año se aprobó la Convención sobre los Derechos del Niño?', '1989', '1810', '1994', '2005'),
      p('¿Qué jerarquía tiene la Convención sobre los Derechos del Niño en Argentina desde 1994?', 'jerarquía constitucional', 'la de una ley provincial', 'la de un decreto', 'ninguna, es solo una recomendación'),
      p('¿Qué ley nacional establece la protección integral de los derechos de niñas, niños y adolescentes?', 'Ley 26.061', 'Ley 26.150', 'Ley 20.744', 'Ley 24.240'),
      p('¿Desde qué edad se puede votar en Argentina?', '16 años', '14 años', '18 años', '21 años'),
      p('¿Qué organización representa a los estudiantes dentro de la escuela?', 'el centro de estudiantes', 'la cooperadora', 'el equipo directivo', 'la inspección'),
      p('Tratar de manera desigual a alguien por su origen es…', 'discriminación', 'tolerancia', 'mediación', 'participación'),
      p('Decir que «todas las chicas son malas para las matemáticas» es un ejemplo de…', 'estereotipo', 'derecho', 'norma', 'mediación'),
      p('¿Qué hace una persona mediadora en un conflicto?', 'ayuda a que las partes lleguen a un acuerdo', 'decide quién tiene razón', 'sanciona al culpable', 'defiende a una de las partes'),
      p('Si a un chico no lo dejan inscribirse en la escuela, ¿qué derecho se vulnera?', 'el derecho a la educación', 'el derecho al voto', 'el derecho de huelga', 'el derecho de propiedad'),
      par('prejuicio', 'estereotipo'),
      par('derecho', 'obligación'),
      par('igualdad', 'equidad'),
      par('norma', 'ley'),
      par('ciudadano', 'habitante'),
      par('discriminación', 'exclusión'),
      par('mediación', 'negociación'),
      par('tolerancia', 'respeto'),
      enc('Nombrá un derecho de los adolescentes', 'educación = 30', 'salud = 20', 'identidad / nombre = 15', 'jugar / recreación / esparcimiento = 12', 'opinar / libertad de expresión / expresarse = 10', 'ser escuchado / ser oído = 8'),
      enc('Una forma de participar en la escuela', 'votar / elecciones = 30', 'centro de estudiantes = 25', 'ser delegado / delegada = 15', 'asambleas = 12', 'proponer ideas / propuestas = 10', 'actos escolares = 8'),
      enc('Algo que hace un centro de estudiantes', 'organizar actividades / eventos = 30', 'representar a los alumnos = 25', 'hacer reclamos = 15', 'recaudar fondos / rifas = 10', 'organizar torneos = 10', 'llevar propuestas a la dirección = 10'),
    ],
  },
  {
    id: 'cc-esi',
    titulo: 'ESI: sexualidad y género', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      t('afectividad', 'Dimensión de la sexualidad ligada a las emociones, los sentimientos y los vínculos'),
      t('buen trato', 'Forma de relacionarse basada en el respeto y el cuidado mutuo'),
      t('consentimiento', 'Acuerdo libre y claro para hacer algo, que se puede retirar en cualquier momento'),
      t('cuidado', 'Hábitos y decisiones para proteger la salud y el bienestar propio y de los demás'),
      t('diversidad', 'Variedad de formas de ser, sentir, vivir y expresarse que existen en una sociedad'),
      t('ESI / educación sexual integral', 'Derecho de los estudiantes a recibir educación sexual en todas las escuelas, establecido por la Ley 26.150'),
      t('equidad de género', 'Igualdad de oportunidades y de trato entre personas de distintos géneros'),
      t('femicidio', 'Asesinato de una mujer por razones de género'),
      t('género', 'Construcción social y cultural sobre los roles asignados a las personas según su sexo'),
      t('identidad de género', 'Vivencia interna de cada persona sobre su género, que puede coincidir o no con el sexo asignado al nacer'),
      t('intimidad', 'Espacio personal que cada persona tiene derecho a proteger de los demás'),
      t('Ley Micaela', 'Ley que establece la capacitación obligatoria en género para quienes trabajan en el Estado'),
      t('machismo', 'Conjunto de actitudes que consideran a los varones superiores a las mujeres'),
      t('matrimonio igualitario', 'Ley de 2010 que permite casarse a personas del mismo sexo'),
      t('Ni Una Menos', 'Movimiento surgido en 2015 contra la violencia hacia las mujeres'),
      t('orientación sexual', 'Atracción afectiva o sexual que una persona siente hacia otras'),
      t('patriarcado', 'Organización social en la que predomina el poder de los varones'),
      t('respeto', 'Consideración y valoración de las demás personas y de sus decisiones'),
      t('sexualidad', 'Dimensión de la persona que incluye el cuerpo, las emociones, los vínculos y la identidad'),
      t('violencia de género', 'Toda conducta que daña a una persona por razones de género'),
      p('¿Qué ley creó el Programa Nacional de Educación Sexual Integral?', 'Ley 26.150', 'Ley 26.061', 'Ley 26.743', 'Ley 27.499'),
      p('¿En qué escuelas es obligatoria la ESI?', 'en todas, públicas y privadas', 'solo en las públicas', 'solo en las secundarias', 'solo si las familias lo piden'),
      p('¿Cuál de estos es uno de los ejes de la ESI?', 'valorar la afectividad', 'aprobar exámenes', 'competir en deportes', 'elegir una carrera'),
      p('¿En qué año se sancionó la Ley de Identidad de Género?', '2012', '1994', '2006', '2020'),
      p('¿En qué año se aprobó el matrimonio igualitario en Argentina?', '2010', '2015', '2002', '1987'),
      p('¿Qué establece la Ley Micaela?', 'capacitación obligatoria en género para quienes trabajan en el Estado', 'ESI en todas las escuelas', 'licencias por nacimiento', 'el cupo laboral trans'),
      p('¿Qué movimiento surgió en 2015 contra la violencia hacia las mujeres?', 'Ni Una Menos', 'Madres de Plaza de Mayo', 'el Mayo Francés', 'la Primavera Árabe'),
      p('¿Qué característica tiene el consentimiento?', 'se puede retirar en cualquier momento', 'vale para siempre', 'se da una sola vez', 'lo puede dar otra persona'),
      p('Revisarle el celular a la pareja sin permiso es una señal de…', 'control en la pareja', 'cuidado', 'confianza', 'respeto'),
      p('¿Qué es el género?', 'una construcción social y cultural', 'una característica biológica', 'una ley', 'un documento'),
      par('sexo', 'género'),
      par('identidad de género', 'orientación sexual'),
      par('igualdad', 'equidad'),
      par('machismo', 'patriarcado'),
      par('femicidio', 'violencia de género'),
      par('intimidad', 'privacidad'),
      par('afectividad', 'sexualidad'),
      par('consentimiento', 'permiso'),
      enc('Un estereotipo de género que escuchaste', 'los hombres no lloran = 30', 'las mujeres son débiles / sexo débil = 20', 'el rosa es de nena / colores de nena = 15', 'las mujeres cocinan / tareas de la casa = 15', 'el fútbol es de varones = 12', 'las mujeres manejan mal = 8'),
      enc('Una señal de noviazgo violento', 'celos / celos excesivos = 30', 'revisar el celular = 25', 'prohibir salir con amigos = 18', 'insultos / gritos = 12', 'controlar la ropa = 10', 'golpes / empujones = 5'),
      enc('Algo que tiene que tener una relación sana', 'respeto = 30', 'confianza = 25', 'comunicación / diálogo = 20', 'libertad = 10', 'amor / cariño = 10', 'consentimiento = 5'),
    ],
  },
  {
    id: 'cc-digital',
    titulo: 'Comunicación, TIC y convivencia digital', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      t('algoritmo', 'Instrucciones que usan las plataformas para decidir qué contenido mostrarte'),
      t('burbuja de filtro', 'Efecto por el que las redes te muestran solo contenidos parecidos a los que ya te gustan'),
      t('ciberbullying / ciberacoso', 'Acoso entre pares a través de redes sociales, mensajes o juegos en línea'),
      t('contraseña', 'Clave secreta que protege una cuenta'),
      t('datos personales', 'Información que identifica a una persona, como su nombre, su DNI o su dirección'),
      t('deepfake', 'Video o audio falso hecho con inteligencia artificial que imita a una persona real'),
      t('desinformación', 'Información falsa que se difunde a propósito para engañar'),
      t('fake news / noticia falsa', 'Noticia inventada o manipulada que se presenta como si fuera verdadera'),
      t('grooming', 'Acoso de una persona adulta a un menor por internet con fines sexuales'),
      t('huella digital', 'Rastro de información que dejamos al usar internet'),
      t('influencer', 'Persona con muchos seguidores que influye en las opiniones y el consumo de otros'),
      t('inteligencia artificial / IA', 'Sistemas informáticos capaces de hacer tareas que parecen requerir inteligencia humana'),
      t('medios de comunicación', 'Canales que llevan información a gran cantidad de personas, como la TV, la radio o los diarios'),
      t('netiqueta', 'Normas de buena conducta en internet'),
      t('phishing', 'Engaño para robar contraseñas o datos haciéndose pasar por otra persona o empresa'),
      t('privacidad', 'Derecho a decidir qué información propia se comparte y con quién'),
      t('sexting', 'Envío de fotos o mensajes de contenido sexual por medios digitales'),
      t('troll', 'Usuario que publica mensajes para provocar o generar peleas'),
      t('verificación / chequeo', 'Comprobar si una información es verdadera consultando fuentes confiables'),
      t('viralización', 'Difusión masiva y muy rápida de un contenido en internet'),
      p('¿Qué es el grooming?', 'el acoso de un adulto a un menor por internet', 'un tipo de virus', 'una red social', 'una pelea entre compañeros'),
      p('¿Qué ley incorporó el grooming como delito al Código Penal?', 'Ley 26.904', 'Ley 26.150', 'Ley 25.326', 'Ley 20.744'),
      p('¿Qué ley protege los datos personales en Argentina?', 'Ley 25.326', 'Ley 26.904', 'Ley 26.061', 'Ley 24.240'),
      p('¿Qué conviene hacer antes de compartir una noticia?', 'verificarla en fuentes confiables', 'compartirla rápido', 'mirar cuántos likes tiene', 'preguntar en un grupo de WhatsApp'),
      p('¿Qué es la huella digital?', 'el rastro que dejamos en internet', 'la huella del dedo para desbloquear el celular', 'una contraseña', 'una aplicación'),
      p('Si alguien te acosa por redes, ¿qué conviene hacer?', 'guardar pruebas y contárselo a un adulto de confianza', 'borrar todo', 'responder con insultos', 'no decirle a nadie'),
      p('Un mail que pide tu contraseña haciéndose pasar por tu banco es…', 'phishing', 'netiqueta', 'viralización', 'un algoritmo'),
      p('¿Qué es una burbuja de filtro?', 'que las redes te muestren solo lo que ya pensás', 'un filtro para fotos', 'un antivirus', 'un grupo privado'),
      p('¿Cuál es la contraseña más segura?', 'una frase larga con números y símbolos', 'tu fecha de nacimiento', '123456', 'tu nombre'),
      p('¿Qué es un deepfake?', 'un video falso hecho con inteligencia artificial', 'una red social', 'un tipo de meme', 'una transmisión en vivo'),
      par('bullying', 'ciberbullying'),
      par('grooming', 'sexting'),
      par('fake news', 'rumor'),
      par('phishing', 'hackeo'),
      par('algoritmo', 'burbuja de filtro'),
      par('influencer', 'celebridad'),
      par('privacidad', 'intimidad'),
      par('troll', 'hater'),
      enc('Una red social o app que usás todos los días', 'Instagram = 30', 'TikTok = 28', 'WhatsApp = 20', 'YouTube = 12', 'Discord = 5', 'X / Twitter = 5'),
      enc('Un peligro de internet', 'grooming = 25', 'estafas / phishing = 20', 'ciberbullying / acoso = 20', 'hackeo / robo de cuentas = 15', 'fake news / noticias falsas = 12', 'adicción = 8'),
      enc('Algo que no hay que compartir en redes', 'dirección / dónde vivís = 30', 'contraseñas = 25', 'fotos íntimas = 20', 'DNI / documento = 10', 'número de teléfono = 10', 'ubicación en tiempo real = 5'),
    ],
  },
  {
    id: 'pyc',
    titulo: 'Estado, democracia y derechos', materia: 'Política y Ciudadanía', curso: '5° año',
    items: [
      t('amparo', 'Acción judicial rápida contra actos que lesionan derechos reconocidos por la Constitución (art. 43)'),
      t('autoritarismo', 'Forma de ejercer el poder sin respetar límites ni libertades'),
      t('Constitución Nacional', 'Ley suprema del país, que organiza el Estado y reconoce derechos y garantías'),
      t('consulta popular', 'Mecanismo por el que el Congreso somete un proyecto de ley al voto de la ciudadanía (art. 40)'),
      t('democracia', 'Forma de gobierno en la que el poder reside en el pueblo'),
      t('división de poderes', 'Separación del poder del Estado en Ejecutivo, Legislativo y Judicial'),
      t('Estado', 'Organización política que ejerce el poder sobre una población en un territorio'),
      t('federalismo', 'Forma de organización en la que el poder se reparte entre el Estado nacional y las provincias'),
      t('gobierno', 'Conjunto de personas que ejercen temporalmente el poder del Estado'),
      t('hábeas corpus', 'Acción judicial que protege a una persona detenida de manera ilegal'),
      t('iniciativa popular', 'Derecho de la ciudadanía a presentar proyectos de ley en la Cámara de Diputados (art. 39)'),
      t('juicio político', 'Procedimiento del Congreso para destituir al presidente, a ministros o a jueces de la Corte'),
      t('legitimidad', 'Aceptación de un poder por parte de la sociedad como justo o válido'),
      t('Ley Sáenz Peña', 'Ley de 1912 que estableció el voto secreto y obligatorio para los varones'),
      t('Nunca Más', 'Informe de la CONADEP de 1984 sobre los crímenes de la última dictadura'),
      t('partido político', 'Organización que busca acceder al gobierno y a través de la cual se postulan candidatos'),
      t('poder', 'Capacidad de influir en las decisiones y la conducta de otras personas'),
      t('república', 'Forma de gobierno con división de poderes, elecciones periódicas y publicidad de los actos'),
      t('soberanía popular', 'Principio según el cual el poder emana del pueblo'),
      t('sufragio', 'Derecho a votar y a ser votado'),
      t('terrorismo de Estado', 'Uso ilegal y sistemático de la violencia por parte del propio Estado contra la población'),
      t('hábeas data', 'Acción judicial para conocer y corregir los datos personales que figuran en registros'),
      p('¿Qué estableció la Ley Sáenz Peña de 1912?', 'el voto secreto y obligatorio para los varones', 'el voto femenino', 'el voto desde los 16 años', 'la reforma de la Constitución'),
      p('¿En qué año votaron las mujeres por primera vez en una elección nacional?', '1951', '1912', '1983', '1994'),
      p('¿En qué año se reformó la Constitución y se dio jerarquía constitucional a los tratados de derechos humanos?', '1994', '1853', '1983', '1949'),
      p('¿Qué artículo de la Constitución habilita la iniciativa popular?', 'el 39', 'el 14 bis', 'el 75', 'el 1'),
      p('¿Cuál de estos NO es un poder del Estado?', 'el Poder Electoral', 'el Poder Ejecutivo', 'el Poder Legislativo', 'el Poder Judicial'),
      p('Detienen a una persona sin orden de un juez. ¿Qué acción corresponde?', 'hábeas corpus', 'hábeas data', 'juicio político', 'iniciativa popular'),
      p('¿Qué organismo elaboró el informe «Nunca Más»?', 'la CONADEP', 'la Corte Suprema', 'el Congreso', 'la ONU'),
      p('¿Qué forma de gobierno adopta la Constitución en su artículo 1?', 'representativa, republicana y federal', 'monárquica', 'parlamentaria', 'unitaria'),
      p('¿En qué año volvió la democracia a la Argentina tras la última dictadura?', '1983', '1976', '1989', '1973'),
      p('¿Qué dice el artículo 22 de la Constitución?', 'el pueblo no delibera ni gobierna sino por medio de sus representantes', 'todos los habitantes son iguales ante la ley', 'nadie puede ser penado sin juicio previo', 'el gobierno federal sostiene el culto católico'),
      par('Estado', 'gobierno'),
      par('legalidad', 'legitimidad'),
      par('poder', 'autoridad'),
      par('amparo', 'hábeas corpus'),
      par('hábeas corpus', 'hábeas data'),
      par('democracia directa', 'democracia representativa'),
      par('iniciativa popular', 'consulta popular'),
      par('república', 'democracia'),
      enc('Un derecho que garantiza la democracia', 'votar / voto / sufragio = 30', 'libertad de expresión = 25', 'igualdad ante la ley / igualdad = 15', 'protestar / manifestarse = 12', 'educación = 10', 'libertad de prensa = 8'),
      enc('Algo que hace el Congreso', 'hacer leyes / sancionar leyes = 40', 'aprobar el presupuesto = 20', 'juicio político = 15', 'debatir = 10', 'aprobar tratados = 10', 'controlar al Poder Ejecutivo = 5'),
      enc('Una forma de participar en política', 'votar = 35', 'militar en un partido = 20', 'marchas / manifestaciones = 15', 'centro de estudiantes = 12', 'firmar petitorios / peticiones = 10', 'ser candidato = 8'),
    ],
  },
  {
    id: 'escape-voto',
    titulo: 'Escape: El voto robado', materia: 'Política y Ciudadanía', curso: '4° a 6° año',
    items: [{
      tipo: 'escape',
      titulo: 'El voto robado',
      minutos: 30,
      intro: 'Faltan pocas horas para la elección del centro de estudiantes y alguien se llevó la urna con todos los votos. Antes de desaparecer, dejó una serie de candados con acertijos sobre la democracia. Tienen 30 minutos para abrirlos, encontrar la urna y salvar la elección. Pueden usar la Constitución Nacional.',
      final: '¡Encontraron la urna! Los votos están a salvo y la elección se puede hacer. Sin voto universal, igual, secreto y obligatorio no hay democracia… y sin participación, tampoco.',
      candados: [
        {
          titulo: 'La puerta de preceptoría', tipo: 'numero', respuesta: '1912',
          desafio: 'En la puerta hay un papel: «La clave es el año de la ley que hizo que el voto fuera secreto y obligatorio para los varones. Antes de esa ley, se votaba cantando el voto en voz alta».',
          pistas: ['La ley lleva el nombre del presidente que la impulsó: Roque Sáenz Peña.', 'Fue dos años antes de que empezara la Primera Guerra Mundial (1914).'],
        },
        {
          titulo: 'El cuaderno de actas', tipo: 'palabra', respuesta: 'representantes',
          desafio: 'En el cuaderno falta una palabra: «El pueblo no delibera ni gobierna sino por medio de sus ______ y autoridades creadas por esta Constitución». La palabra que falta abre el candado.',
          pistas: ['Es el artículo 22 de la Constitución Nacional.', 'Son las personas que elegimos con el voto: diputados, senadores, presidente…'],
        },
        {
          titulo: 'El armario de la dirección', tipo: 'direccion', respuesta: 'arriba,abajo,derecha,arriba',
          desafio: 'En el armario hay un cartel: «Cada poder tiene su flecha: el Legislativo ↑, el Ejecutivo → y el Judicial ↓». Debajo, el ladrón escribió: «Primero el que hace las leyes, después el que resuelve los conflictos cuando no se cumplen, luego el que las pone en práctica y al final, otra vez, el que las hace».',
          pistas: ['Son 4 flechas. La primera y la última son iguales.', 'Hacer leyes: Legislativo. Resolver conflictos: Judicial. Poner en práctica: Ejecutivo.'],
        },
        {
          titulo: 'La caja fuerte', tipo: 'numero', respuesta: '117',
          desafio: 'La caja fuerte pide un número de 3 cifras. Una nota dice: «Sumá los números de los artículos de la Constitución que tratan sobre los partidos políticos, la iniciativa popular y la consulta popular».',
          pistas: ['Los tres artículos están seguidos, justo después del que habla del sufragio (el 37).', 'Partidos políticos: 38. Iniciativa popular: 39. Consulta popular: 40.'],
        },
        {
          titulo: 'El candado de colores', tipo: 'color', respuesta: 'rojo,azul,verde,amarillo',
          desafio: 'El artículo 37 dice que el sufragio es universal (azul), igual (verde), secreto (rojo) y obligatorio (amarillo). El ladrón los desordenó: el código empieza por el que asegura que nadie sepa a quién votaste, sigue el que dice que todos pueden votar, después el que hace que cada voto valga lo mismo y termina con el que nos obliga a votar.',
          pistas: ['Son 4 colores, uno por cada característica del voto.', 'Secreto → universal → igual → obligatorio.'],
        },
        {
          titulo: 'La urna', tipo: 'palabra', respuesta: 'democracia',
          desafio: 'Encontraron la urna, pero tiene un último candado: «La palabra es la forma de gobierno en la que el poder reside en el pueblo. Argentina la recuperó en 1983 y la tenemos que cuidar entre todos».',
          pistas: ['Viene del griego: demos (pueblo) y kratos (poder).', 'Tiene 10 letras y empieza con D.'],
        },
      ],
    }],
  },
  {
    id: 'escape-red',
    titulo: 'Escape: Rescate en la red', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [{
      tipo: 'escape',
      titulo: 'Rescate en la red',
      minutos: 25,
      intro: 'Tomi, de 2° año, está recibiendo mensajes de alguien que dice tener 14 años y le pide fotos. Encima, le robaron la cuenta de Instagram. Tomi no sabe qué hacer y tiene miedo de contarlo. Tienen 25 minutos para entender qué está pasando, proteger su cuenta y llegar a la denuncia. Cada candado les da un número: guárdenlo, lo van a necesitar al final.',
      final: '¡Lo lograron! Tomi guardó las pruebas, bloqueó al acosador, le contó a su familia y hicieron la denuncia. El grooming es un delito (Ley 26.904) y nunca es culpa de quien lo sufre: pedir ayuda a un adulto de confianza es el primer paso.',
      candados: [
        {
          titulo: 'El chat sospechoso', tipo: 'palabra', respuesta: 'grooming',
          desafio: 'El supuesto chico de 14 años le escribe a Tomi todos los días, le hace regalos en un juego online y le pide que «no le cuente a nadie, que es un secreto entre ellos». Ahora le pide fotos. En realidad es un adulto. ¿Cómo se llama esta forma de acoso?',
          pistas: ['Es una palabra en inglés que se usa también en la ley argentina.', 'Empieza con G y tiene 8 letras.'],
          recompensa: 'Primer número de la ley final: 2',
          fisica: 'Mensaje encontrado en el celular de Tomi: «No le digas a nadie, esto es entre nosotros». Un adulto que pide secreto es una señal de alerta.',
        },
        {
          titulo: 'Las contraseñas', tipo: 'numero', respuesta: '2',
          desafio: 'Tomi usaba «123456». Estas son las opciones para su nueva contraseña:\na) Tomi2010\nb) M1Perro!Duerme#Siesta\nc) contraseña123\nd) 9Lunas&Tres_Gatos$\ne) QWERTY\n¿Cuántas cumplen TODAS estas reglas: al menos 12 caracteres, mayúsculas, minúsculas, números y símbolos?',
          pistas: ['Contá los caracteres de cada una y fijate si tiene símbolos como ! # & _ $.', 'Solo la b y la d cumplen todo.'],
          recompensa: 'Segundo número de la ley final: 6',
        },
        {
          titulo: 'Qué hacer primero', tipo: 'direccion', respuesta: 'arriba,abajo,derecha,izquierda',
          desafio: 'Si alguien te acosa por internet hay cuatro cosas para hacer, cada una con su flecha:\nGuardar pruebas (capturas) ↑ · Bloquear al acosador ↓ · Contarle a un adulto de confianza → · Hacer la denuncia ←\nIngresen las flechas en el orden correcto.',
          pistas: ['Si bloqueás primero, podés perder la conversación que sirve como prueba.', 'Pruebas → bloquear → adulto → denuncia.'],
          recompensa: 'Tercer número de la ley final: 9',
        },
        {
          titulo: 'El semáforo de la privacidad', tipo: 'color', respuesta: 'rojo,verde,amarillo,rojo',
          desafio: 'Clasifiquen cuatro datos con el semáforo: verde = se puede compartir, amarillo = con cuidado (dice dónde estás), rojo = nunca. Cada integrante del equipo tiene en su celular uno o más de los datos: juntenlos en orden y marquen los colores.',
          partes: ['Dato 1: tu dirección.', 'Dato 2: tu banda favorita.', 'Dato 3: una foto en el patio con el uniforme de la escuela.', 'Dato 4: tu contraseña.'],
          pistas: ['La dirección y la contraseña no se comparten nunca.', 'Rojo, verde, amarillo, rojo.'],
          recompensa: 'Cuarto número de la ley final: 0',
        },
        {
          titulo: 'El mail falso', tipo: 'palabra', respuesta: 'phishing',
          desafio: 'Tomi recibió un mail «de Instagram» que decía que su cuenta iba a ser cerrada si no ingresaba su contraseña en un link. Así le robaron la cuenta. ¿Cómo se llama este engaño?',
          pistas: ['Suena como «pescar» en inglés: te tiran un anzuelo.', 'Empieza con PH.'],
          recompensa: 'Quinto número de la ley final: 4',
        },
        {
          titulo: 'La denuncia', tipo: 'numero', respuesta: '26904',
          desafio: 'Para hacer la denuncia necesitan el número de la ley que incorporó el grooming como delito al Código Penal. Lo fueron armando con los números que les dio cada candado.',
          pistas: ['Juntá los números en el orden de los candados.', 'Es la Ley 26.904.'],
        },
      ],
    }],
  },
  {
    id: 'escape-paritaria',
    titulo: 'Escape: La paritaria bloqueada', materia: 'Trabajo y Ciudadanía', curso: '6° año',
    items: [{
      tipo: 'escape',
      titulo: 'La paritaria bloqueada',
      minutos: 30,
      intro: 'En la textil «Hilos del Sur» nadie cobró el aguinaldo, hay compañeros sin recibo de sueldo y la paritaria está trabada. Antes de irse, la delegada gremial dejó una carpeta con las pruebas… cerrada con candados. Tienen 30 minutos para abrirla y armar el reclamo.',
      final: '¡Abrieron la carpeta! Con los recibos, el artículo 14 bis y la organización del sindicato, los trabajadores de Hilos del Sur pueden reclamar lo que les corresponde. Los derechos laborales se conquistaron colectivamente y se defienden igual.',
      candados: [
        {
          titulo: 'El recibo de junio', tipo: 'numero', respuesta: '300',
          desafio: 'Un recibo muestra que el mejor sueldo del primer semestre fue de $600.000. El aguinaldo (SAC) de junio es la mitad del mejor sueldo del semestre. ¿Cuántos MILES de pesos le corresponden de aguinaldo?',
          pistas: ['SAC = mejor sueldo del semestre ÷ 2.', '600.000 ÷ 2 = 300.000. Escribí solo los miles.'],
          recompensa: 'Prueba 1: el aguinaldo adeudado es de $300.000 por trabajador.',
        },
        {
          titulo: 'El cartel del portón', tipo: 'palabra', respuesta: 'huelga',
          desafio: 'En el portón pegaron el artículo 14 bis, pero la última palabra está tapada: «Queda garantizado a los gremios: concertar convenios colectivos de trabajo; recurrir a la conciliación y al arbitraje; el derecho de ______».',
          pistas: ['Es la medida de fuerza en la que se deja de trabajar para reclamar.', 'Empieza con H y tiene 6 letras.'],
          recompensa: 'Prueba 2: la Constitución protege la organización y la protesta de los trabajadores.',
        },
        {
          titulo: 'Las fichas del personal', tipo: 'color', respuesta: 'rojo,verde,rojo,verde',
          desafio: 'En la carpeta hay cuatro fichas del personal. Marquen en verde las que muestran un derecho respetado y en rojo las que muestran un derecho vulnerado. Cada integrante del equipo tiene en su celular una o más fichas: léanlas en voz alta, en orden.',
          partes: ['Ficha 1: Ana trabaja hace dos años sin recibo de sueldo.', 'Ficha 2: Luis se tomó 14 días de vacaciones pagas.', 'Ficha 3: a Carla la despidieron sin causa y sin indemnización.', 'Ficha 4: Pedro tiene obra social y ART.'],
          pistas: ['Trabajar sin recibo y un despido sin indemnización son derechos vulnerados.', 'Rojo, verde, rojo, verde.'],
          recompensa: 'Prueba 3: hay trabajo no registrado y despidos sin indemnización.',
        },
        {
          titulo: 'El camino del conflicto', tipo: 'direccion', respuesta: 'arriba,derecha,abajo,izquierda',
          desafio: 'Cada etapa de un conflicto laboral tiene su flecha: Negociación paritaria ↑ · Conciliación obligatoria (la dicta el Estado) → · Huelga ↓ · Firma del acuerdo ←\nIngresen las flechas en el orden en que suele avanzar un conflicto que se traba.',
          pistas: ['Primero se negocia; si no hay acuerdo, interviene el Estado.', 'Negociación → conciliación → huelga → acuerdo.'],
          recompensa: 'Prueba 4: el reclamo puede seguir el camino legal hasta un acuerdo.',
        },
        {
          titulo: 'La carpeta', tipo: 'palabra', respuesta: 'sindicato',
          desafio: 'El último candado pide el nombre de la organización que agrupa a los trabajadores de una actividad para defender sus derechos y negociar los convenios colectivos.',
          pistas: ['La delegada gremial pertenece a esta organización.', 'Empieza con S y tiene 9 letras.'],
        },
      ],
    }],
  },
  {
    id: 'escape-contrato',
    titulo: 'Escape: El contrato trampa', materia: 'Derecho', curso: '5° año · Economía y Administración',
    items: [{
      tipo: 'escape',
      titulo: 'El contrato trampa',
      minutos: 30,
      intro: 'Sofía se anotó en un gimnasio y ahora que se quiere dar de baja le cobran una multa equivalente a un año de cuota: «lo dice el contrato que firmaste». Su hermano, estudiante de abogacía, dejó el expediente cerrado con candados antes de irse a rendir. Tienen 30 minutos para descubrir si esa cláusula vale y cómo defenderla.',
      final: '¡Caso resuelto! La multa es una cláusula abusiva: se tiene por no escrita. Con la Ley 24.240 y el principio de interpretación a favor del consumidor, Sofía puede darse de baja sin pagarla.',
      candados: [
        {
          titulo: 'La fecha del contrato', tipo: 'numero', respuesta: '2015',
          desafio: 'El contrato cita el Código Civil y Comercial que unificó el derecho civil y el comercial. ¿En qué año entró en vigencia?',
          pistas: ['Reemplazó al Código de Vélez Sarsfield, que regía desde 1871.', 'Entró en vigencia el 1° de agosto de ese año, poco más de una década después de 2004.'],
        },
        {
          titulo: 'La ley del consumidor', tipo: 'numero', respuesta: '240',
          desafio: 'En la tapa del expediente dice «Ley 24.___». Es la Ley de Defensa del Consumidor. Completen las tres cifras que faltan.',
          pistas: ['Es de 1993.', 'Ley 24.240.'],
          recompensa: 'La Ley 24.240 protege a quien compra o usa un servicio como destinatario final.',
        },
        {
          titulo: 'La cláusula', tipo: 'palabra', respuesta: 'abusiva / abusivas',
          desafio: 'Una cláusula que impone al consumidor una carga desproporcionada, como una multa de un año de cuota por darse de baja, es una cláusula ______. Se tiene por no escrita.',
          pistas: ['Es alguien que se aprovecha de otro: abusa.', 'Empieza con A y tiene 7 letras.'],
          recompensa: 'La cláusula de la multa no vale: se tiene por no escrita.',
        },
        {
          titulo: 'La pirámide', tipo: 'color', respuesta: 'rojo,azul,verde,amarillo',
          desafio: 'Ordenen estas normas de MAYOR a MENOR jerarquía: contrato entre las partes (amarillo), decreto del Poder Ejecutivo (verde), Constitución Nacional (rojo), ley del Congreso (azul).',
          pistas: ['Arriba de todo está la Constitución (art. 31).', 'Constitución → ley → decreto → contrato.'],
        },
        {
          titulo: 'El reclamo', tipo: 'direccion', respuesta: 'izquierda,arriba,derecha,abajo',
          desafio: 'Cada paso del reclamo tiene su flecha: Reclamo por escrito a la empresa ← · Denuncia en Defensa del Consumidor ↑ · Audiencia de conciliación → · Juicio ↓\nIngresen el orden en que conviene avanzar.',
          pistas: ['Primero se intenta arreglar directamente con la empresa.', 'Reclamo → denuncia → audiencia → juicio.'],
        },
        {
          titulo: 'El principio final', tipo: 'palabra', respuesta: 'consumidor',
          desafio: 'Para cerrar el caso: si hay dudas sobre cómo interpretar el contrato, se interpreta en el sentido más favorable al ______ (in dubio pro ______).',
          pistas: ['Es Sofía en esta historia.', 'Empieza con C y tiene 10 letras.'],
        },
      ],
    }],
  },
  {
    id: 'tyc',
    titulo: 'Derechos laborales y mundo del trabajo', materia: 'Trabajo y Ciudadanía', curso: '6° año',
    items: [
      t('aguinaldo / SAC', 'Sueldo anual complementario que se paga en dos cuotas, en junio y en diciembre'),
      t('aportes', 'Parte del salario que se descuenta para la jubilación y la obra social'),
      t('ART / aseguradora de riesgos del trabajo', 'Aseguradora que cubre los accidentes y las enfermedades laborales'),
      t('convenio colectivo', 'Acuerdo entre sindicatos y empleadores que fija salarios y condiciones de trabajo de una actividad'),
      t('cooperativa', 'Empresa de propiedad colectiva en la que los socios deciden de forma democrática'),
      t('desocupación / desempleo', 'Situación de quienes buscan trabajo activamente y no lo consiguen'),
      t('economía social', 'Formas de producción basadas en la cooperación y no en el lucro'),
      t('empleo', 'Trabajo que se hace a cambio de un salario, en relación de dependencia'),
      t('flexibilización laboral', 'Reducción de las protecciones legales del trabajador para abaratar costos'),
      t('fordismo', 'Modelo de producción en cadena de montaje, en serie y a gran escala'),
      t('huelga / paro', 'Medida de fuerza en la que los trabajadores dejan de trabajar para reclamar'),
      t('indemnización', 'Pago que recibe el trabajador cuando lo despiden sin causa justificada'),
      t('informalidad / trabajo no registrado', 'Trabajo sin registrar, sin aportes ni protección legal (trabajo «en negro»)'),
      t('jubilación', 'Ingreso que recibe una persona al retirarse de la vida laboral'),
      t('licencia', 'Permiso para faltar al trabajo sin perder el salario, por ejemplo por enfermedad o nacimiento'),
      t('monotributo', 'Régimen simplificado de impuestos para trabajadores independientes'),
      t('obra social', 'Entidad que brinda cobertura de salud a los trabajadores y sus familias'),
      t('paritarias', 'Negociaciones periódicas entre sindicatos y empleadores para fijar salarios'),
      t('recibo de sueldo', 'Documento que detalla el salario y los descuentos del trabajador'),
      t('salario mínimo, vital y móvil', 'Menor remuneración que puede cobrar un trabajador en relación de dependencia'),
      t('sindicato', 'Organización que agrupa a trabajadores para defender sus derechos'),
      t('tareas de cuidado', 'Trabajo de atender a niños, personas mayores o enfermas y sostener el hogar, muchas veces sin paga'),
      t('toyotismo', 'Modelo de producción flexible y «justo a tiempo» surgido en Japón'),
      t('vacaciones', 'Descanso anual pago al que tiene derecho todo trabajador registrado'),
      t('trabajo decente', 'Concepto de la OIT: trabajo productivo, con ingreso justo, protección social y derechos'),
      p('¿Qué artículo de la Constitución reconoce los derechos del trabajador y el derecho de huelga?', 'el 14 bis', 'el 16', 'el 22', 'el 75'),
      p('¿Qué ley regula el trabajo en relación de dependencia?', 'la Ley de Contrato de Trabajo (20.744)', 'la Ley de Defensa del Consumidor', 'la Ley de ESI', 'la Ley de Protección Integral'),
      p('¿Desde qué edad se permite trabajar en Argentina?', '16 años', '14 años', '12 años', '18 años'),
      p('¿Cuándo se paga el aguinaldo?', 'en junio y en diciembre', 'en enero', 'cada tres meses', 'cuando lo decide el empleador'),
      p('¿Qué organización internacional promueve el «trabajo decente»?', 'la OIT', 'la FIFA', 'la OTAN', 'el FMI'),
      p('Trabajar sin recibo de sueldo ni aportes es…', 'trabajo no registrado', 'trabajo decente', 'monotributo', 'una paritaria'),
      p('¿Qué cubre la ART?', 'los accidentes y las enfermedades laborales', 'las vacaciones', 'el aguinaldo', 'la jubilación'),
      p('¿Qué es una paritaria?', 'una negociación salarial entre sindicatos y empleadores', 'una huelga', 'un despido', 'un impuesto'),
      p('El modelo de producción en cadena de montaje se conoce como…', 'fordismo', 'toyotismo', 'cooperativismo', 'feudalismo'),
      p('¿Qué organismo mide la desocupación en Argentina?', 'el INDEC', 'el Banco Central', 'la ANSES', 'la Corte Suprema'),
      par('trabajo', 'empleo'),
      par('desocupación', 'subocupación'),
      par('sindicato', 'cooperativa'),
      par('fordismo', 'toyotismo'),
      par('trabajo informal', 'trabajo precario'),
      par('jubilación', 'pensión'),
      par('convenio colectivo', 'paritaria'),
      par('obra social', 'ART'),
      enc('Un derecho del trabajador', 'vacaciones = 25', 'aguinaldo = 20', 'salario / sueldo = 20', 'obra social = 12', 'jubilación / aportes = 10', 'licencias = 8', 'indemnización = 5'),
      enc('Un trabajo que te gustaría tener', 'médico / médica = 20', 'docente / profesor / profesora = 18', 'programador / programadora = 15', 'abogado / abogada = 12', 'futbolista = 12', 'psicólogo / psicóloga = 10', 'influencer / streamer = 8'),
      enc('Algo que aparece en un recibo de sueldo', 'sueldo básico / salario = 30', 'descuentos = 20', 'aportes jubilatorios / jubilación = 15', 'obra social = 15', 'antigüedad = 10', 'horas extra = 10'),
    ],
  },
  {
    id: 'derecho',
    titulo: 'Introducción al derecho', materia: 'Derecho', curso: '5° año · Economía y Administración',
    items: [
      t('acto jurídico', 'Acto voluntario y lícito cuyo fin es crear, modificar o extinguir relaciones jurídicas'),
      t('capacidad de derecho', 'Aptitud de toda persona para ser titular de derechos y deberes'),
      t('capacidad de ejercicio', 'Aptitud para ejercer por sí mismo los propios derechos'),
      t('Código Civil y Comercial', 'Código vigente desde 2015 que unificó el derecho civil y el comercial'),
      t('contrato', 'Acuerdo de dos o más partes para crear, modificar o extinguir relaciones patrimoniales'),
      t('costumbre', 'Fuente del derecho formada por prácticas repetidas que la comunidad considera obligatorias'),
      t('doctrina', 'Opiniones y estudios de los especialistas en derecho'),
      t('domicilio', 'Atributo de la persona: lugar donde reside de forma habitual'),
      t('fuentes del derecho', 'Origen de las normas jurídicas: la ley, la costumbre, la jurisprudencia y la doctrina'),
      t('hecho jurídico', 'Acontecimiento que produce el nacimiento, la modificación o la extinción de relaciones jurídicas'),
      t('jurisprudencia', 'Conjunto de fallos de los tribunales que resuelven casos parecidos de la misma manera'),
      t('ley', 'Norma general y obligatoria dictada por el Poder Legislativo'),
      t('nombre', 'Atributo de la persona formado por el prenombre y el apellido'),
      t('norma jurídica', 'Regla de conducta obligatoria cuyo incumplimiento tiene una sanción'),
      t('obligación', 'Relación jurídica en la que el deudor debe cumplir una prestación a favor del acreedor'),
      t('patrimonio', 'Conjunto de bienes con valor económico de una persona'),
      t('persona jurídica', 'Ente al que la ley le reconoce aptitud para adquirir derechos y contraer obligaciones, como una sociedad'),
      t('prescripción', 'Adquisición o pérdida de derechos por el paso del tiempo'),
      t('sanción', 'Consecuencia que se aplica a quien no cumple una norma'),
      t('sociedad anónima', 'Tipo de sociedad cuyo capital se divide en acciones'),
      t('vigencia', 'Período durante el cual una norma es obligatoria'),
      t('Kelsen / pirámide jurídica', 'Jurista que representó el orden jerárquico de las normas con una pirámide'),
      p('Si una ley no indica otra fecha, ¿desde cuándo rige?', 'después del octavo día de su publicación oficial', 'desde que se sanciona', 'al mes de publicada', 'al año de publicada'),
      p('¿A qué edad se alcanza la mayoría de edad en Argentina?', '18 años', '21 años', '16 años', '13 años'),
      p('Según el Código Civil y Comercial, ¿desde qué edad una persona es adolescente?', '13 años', '12 años', '16 años', '15 años'),
      p('¿En qué año entró en vigencia el Código Civil y Comercial actual?', '2015', '1871', '1994', '2010'),
      p('¿Qué norma está en la cima de la pirámide jurídica argentina?', 'la Constitución Nacional', 'las leyes', 'los decretos', 'las ordenanzas municipales'),
      p('Los fallos repetidos de los tribunales sobre casos parecidos se llaman…', 'jurisprudencia', 'doctrina', 'costumbre', 'legislación'),
      p('¿Cuál de estas es una persona jurídica?', 'una sociedad anónima', 'un recién nacido', 'un juez', 'un adolescente'),
      p('¿Qué ley protege los derechos de los consumidores?', 'Ley 24.240', 'Ley 20.744', 'Ley 26.994', 'Ley 25.326'),
      p('¿Cuál NO es un atributo de la persona?', 'la profesión', 'el nombre', 'el domicilio', 'la capacidad'),
      p('Comprar un celular en un comercio es un ejemplo de…', 'contrato', 'hecho jurídico natural', 'delito', 'costumbre'),
      par('persona humana', 'persona jurídica'),
      par('capacidad de derecho', 'capacidad de ejercicio'),
      par('derecho objetivo', 'derecho subjetivo'),
      par('hecho jurídico', 'acto jurídico'),
      par('doctrina', 'jurisprudencia'),
      par('ley', 'decreto'),
      par('sociedad anónima', 'SRL'),
      par('derecho público', 'derecho privado'),
      enc('Un atributo de la persona', 'nombre = 30', 'domicilio = 25', 'capacidad = 15', 'estado civil / estado = 12', 'patrimonio = 10', 'nacionalidad = 8'),
      enc('Un contrato que hacemos en la vida cotidiana', 'compraventa / comprar = 35', 'alquiler / locación = 25', 'trabajo / contrato de trabajo = 15', 'transporte / viajar en colectivo = 10', 'seguro = 8', 'préstamo = 7'),
      enc('Una fuente del derecho', 'ley = 40', 'costumbre = 25', 'jurisprudencia = 20', 'doctrina = 15'),
    ],
  },
  {
    id: 'celula',
    titulo: 'La célula (ejemplo)', materia: 'Biología', curso: '2° año',
    items: [
      t('ADN', 'Molécula que contiene la información genética'),
      t('bacteria', 'Organismo unicelular procariota'),
      t('cloroplasto', 'Orgánulo donde ocurre la fotosíntesis'),
      t('difusión', 'Paso de sustancias desde donde hay más concentración hacia donde hay menos'),
      t('eucariota', 'Célula que tiene un núcleo definido'),
      t('fotosíntesis', 'Proceso por el cual las plantas fabrican su alimento usando la luz'),
      t('glucosa', 'Azúcar que las células usan como principal fuente de energía'),
      t('hongo', 'Reino al que pertenecen las levaduras y el moho'),
      t('lisosoma', 'Orgánulo que digiere sustancias dentro de la célula'),
      t('mitocondria', 'Orgánulo donde se produce la energía de la célula'),
      t('núcleo', 'Parte de la célula que guarda el material genético'),
      t('ósmosis', 'Paso de agua a través de una membrana semipermeable'),
      t('pared celular', 'Capa rígida que rodea a la célula vegetal'),
      t('ribosoma', 'Estructura donde se fabrican las proteínas'),
      t('tejido', 'Conjunto de células parecidas que cumplen una misma función'),
      t('vacuola', 'Orgánulo que almacena agua y otras sustancias'),
      t('citoplasma', 'Medio acuoso donde flotan los orgánulos de la célula'),
      p('¿Qué orgánulo produce la energía de la célula?', 'mitocondria', 'ribosoma', 'vacuola', 'núcleo'),
      p('¿Cuál de estos organismos NO tiene núcleo definido?', 'una bacteria', 'un hongo', 'una planta', 'un animal'),
      p('¿Qué estructura tienen las células vegetales pero no las animales?', 'pared celular', 'membrana plasmática', 'citoplasma', 'ribosomas'),
      p('¿Qué gas liberan las plantas durante la fotosíntesis?', 'oxígeno', 'dióxido de carbono', 'nitrógeno', 'hidrógeno'),
      p('¿Dónde se fabrican las proteínas?', 'en los ribosomas', 'en los lisosomas', 'en las vacuolas', 'en la pared celular'),
      p('¿Cuál es la unidad básica de todos los seres vivos?', 'la célula', 'el átomo', 'el tejido', 'el órgano'),
      par('mitosis', 'meiosis'),
      par('célula animal', 'célula vegetal'),
      par('ósmosis', 'difusión'),
      par('cloroplasto', 'mitocondria'),
      par('virus', 'bacteria'),
      par('procariota', 'eucariota'),
      enc('Nombrá una parte de la célula', 'núcleo = 30', 'mitocondria = 22', 'membrana / membrana plasmática = 18', 'citoplasma = 12', 'ribosoma = 10', 'cloroplasto = 8'),
    ],
  },
];


// ── Verdadero o falso (¿Cuánto apostás?) y consignas para debatir (Termómetro) ──
const vf = (texto, verdadera, explicacion = '') => ({ tipo: 'afirmacion', texto, verdadera, explicacion });
const deb = (texto) => ({ tipo: 'debate', texto });

const EXTRA = {
  'cc-derechos': [
    vf('Los menores de 18 años no tienen derechos hasta ser adultos.', false, 'Desde la Convención sobre los Derechos del Niño y la Ley 26.061, niñas, niños y adolescentes son sujetos de derecho.'),
    vf('A los 16 años se puede votar en las elecciones nacionales.', true, 'Desde 2012 (Ley 26.774) el voto es optativo entre los 16 y los 18 años.'),
    vf('Votar a los 16 años es obligatorio.', false, 'Entre los 16 y los 18 años el voto es optativo.'),
    vf('El centro de estudiantes lo eligen los propios alumnos.', true, 'Se elige por el voto de los estudiantes de la escuela.'),
    vf('La Convención sobre los Derechos del Niño tiene jerarquía constitucional en la Argentina.', true, 'Desde la reforma de 1994 (artículo 75, inciso 22).'),
    vf('Un estereotipo y un prejuicio son exactamente lo mismo.', false, 'El estereotipo es una imagen generalizada sobre un grupo; el prejuicio es un juicio, casi siempre negativo, antes de conocer.'),
    vf('Los extranjeros que viven en la Argentina tienen los mismos derechos civiles que los ciudadanos.', true, 'Lo dice el artículo 20 de la Constitución Nacional.'),
    vf('Participar solo sirve si uno es mayor de edad.', false, 'La participación empieza en la escuela: asambleas, centro de estudiantes, delegados.'),
    deb('Los celulares deberían estar permitidos en clase.'),
    deb('Los estudiantes deberían votar las normas de convivencia de la escuela.'),
    deb('Votar a los 16 años debería ser obligatorio.'),
    deb('El uniforme escolar debería ser obligatorio.'),
  ],
  'cc-esi': [
    vf('La ESI solo trata sobre biología y reproducción.', false, 'Tiene cinco ejes: cuidar el cuerpo y la salud, valorar la afectividad, garantizar la equidad de género, respetar la diversidad y ejercer nuestros derechos.'),
    vf('La ESI es obligatoria también en las escuelas privadas.', true, 'La Ley 26.150 alcanza a todas las escuelas del país, de gestión estatal y privada.'),
    vf('Si alguien dijo que sí una vez, ya no puede cambiar de opinión.', false, 'El consentimiento se puede retirar en cualquier momento.'),
    vf('Los celos excesivos son una muestra de amor.', false, 'Pueden ser una señal de control en la pareja.'),
    vf('La identidad de género puede no coincidir con el sexo asignado al nacer.', true, 'Así lo reconoce la Ley de Identidad de Género (26.743, de 2012).'),
    vf('En la Argentina, dos personas del mismo sexo se pueden casar.', true, 'Desde 2010, con la ley de matrimonio igualitario.'),
    vf('El género es algo exclusivamente biológico.', false, 'El género es una construcción social y cultural.'),
    vf('Revisarle el celular a la pareja sin permiso es una forma de control.', true, 'Es una de las señales de alerta de un noviazgo violento.'),
    deb('Los chistes machistas son solo chistes.'),
    deb('Las publicidades refuerzan los estereotipos de género.'),
    deb('Varones y mujeres deberían hacer los mismos deportes en Educación Física.'),
    deb('Los celos son normales en una pareja.'),
  ],
  'cc-digital': [
    vf('Si borro una foto de internet, desaparece para siempre.', false, 'Pueden quedar capturas, copias y registros: la huella digital es difícil de borrar.'),
    vf('El grooming es un delito en la Argentina.', true, 'Lo incorporó al Código Penal la Ley 26.904, de 2013.'),
    vf('Una noticia con muchos «me gusta» es confiable.', false, 'La cantidad de likes no dice nada sobre si es verdadera: hay que verificarla en fuentes confiables.'),
    vf('Usar la misma contraseña en todas las cuentas es seguro si la contraseña es difícil.', false, 'Si roban una cuenta, pueden entrar a todas las demás.'),
    vf('Las redes sociales eligen con algoritmos qué contenido mostrarte.', true, 'Por eso cada persona ve cosas distintas y se forman burbujas de filtro.'),
    vf('Compartir una foto íntima de otra persona sin su permiso es una forma de violencia.', true, 'La Ley Olimpia (27.736, de 2023) reconoce la violencia digital.'),
    vf('Un deepfake puede imitar la voz y la cara de una persona real.', true, 'Por eso conviene desconfiar de videos y audios sorprendentes y chequear la fuente.'),
    vf('Si un desconocido te pide que guardes un secreto, conviene contárselo a un adulto de confianza.', true, 'Pedir secreto es una señal de alerta del grooming.'),
    deb('Los menores de 13 años no deberían tener redes sociales.'),
    deb('Las redes sociales hacen más mal que bien.'),
    deb('Usar inteligencia artificial para hacer la tarea es hacer trampa.'),
    deb('Las escuelas deberían prohibir los celulares.'),
  ],
  pyc: [
    vf('El voto en la Argentina es secreto.', true, 'El artículo 37 de la Constitución dice que el sufragio es universal, igual, secreto y obligatorio.'),
    vf('La Constitución Nacional se sancionó en 1853.', true, 'Tuvo varias reformas; la más reciente, en 1994.'),
    vf('El presidente puede disolver el Congreso.', false, 'La Constitución no lo permite: hay división de poderes.'),
    vf('La iniciativa popular permite a la ciudadanía presentar proyectos de ley.', true, 'Está en el artículo 39 de la Constitución.'),
    vf('Las mujeres votan en elecciones nacionales desde 1912.', false, 'El voto femenino se aprobó en 1947 (Ley 13.010) y las mujeres votaron por primera vez en 1951.'),
    vf('Legal y legítimo significan lo mismo.', false, 'Legal es lo que respeta las leyes; legítimo es lo que la sociedad acepta como justo o válido.'),
    vf('La última dictadura militar gobernó entre 1976 y 1983.', true, 'La democracia volvió el 10 de diciembre de 1983.'),
    vf('En una república, los actos de gobierno tienen que ser públicos.', true, 'La publicidad de los actos es uno de los principios republicanos.'),
    deb('El voto debería ser optativo para todas las edades.'),
    deb('Los jueces deberían ser elegidos por el voto popular.'),
    deb('Las redes sociales mejoran la participación política.'),
    deb('Cortar una calle es una forma legítima de reclamo.'),
  ],
  tyc: [
    vf('Si trabajo «en negro» no tengo ningún derecho.', false, 'Los derechos existen igual: el empleador está en falta y se puede reclamar la registración.'),
    vf('El aguinaldo se paga en dos cuotas: en junio y en diciembre.', true, 'Cada cuota es la mitad del mejor sueldo del semestre.'),
    vf('La edad mínima general para trabajar en la Argentina es 16 años.', true, 'La fijó la Ley 26.390, que prohíbe el trabajo infantil.'),
    vf('El derecho de huelga está en la Constitución.', true, 'Lo garantiza el artículo 14 bis.'),
    vf('Las vacaciones pagas son un beneficio que el empleador puede dar o no.', false, 'Son un derecho de todo trabajador registrado (Ley de Contrato de Trabajo).'),
    vf('Una persona desocupada es cualquiera que no trabaja.', false, 'Desocupado es quien no tiene trabajo y lo busca activamente.'),
    vf('Las tareas de cuidado son trabajo, aunque no se paguen.', true, 'Cuidar a niños, personas mayores o enfermas y sostener el hogar es trabajo, muchas veces invisible.'),
    vf('Un monotributista trabaja en relación de dependencia.', false, 'El monotributo es un régimen para trabajadores independientes.'),
    deb('La jornada laboral debería reducirse a 6 horas.'),
    deb('Las tareas de cuidado deberían tener un salario.'),
    deb('Las aplicaciones de reparto les dan libertad a quienes trabajan en ellas.'),
    deb('La tecnología va a quitar más trabajos de los que crea.'),
  ],
  derecho: [
    vf('La costumbre es una fuente del derecho.', true, 'Junto con la ley, la jurisprudencia y la doctrina.'),
    vf('Las leyes rigen desde el momento en que se sancionan.', false, 'Si no dicen otra cosa, rigen después del octavo día de su publicación oficial.'),
    vf('Una sociedad anónima es una persona jurídica.', true, 'La ley le reconoce aptitud para adquirir derechos y contraer obligaciones.'),
    vf('La doctrina es el conjunto de fallos de los tribunales.', false, 'Eso es la jurisprudencia; la doctrina son las opiniones de los especialistas.'),
    vf('El Código Civil y Comercial vigente es de 1871.', false, 'El actual entró en vigencia en 2015; el de 1871 era el de Vélez Sarsfield.'),
    vf('Un contrato puede celebrarse en forma verbal.', true, 'Salvo que la ley exija una forma determinada, como la escritura para vender un inmueble.'),
    vf('En un contrato de consumo, una cláusula abusiva se tiene por no escrita.', true, 'Así lo establecen la Ley 24.240 y el Código Civil y Comercial.'),
    vf('A los 18 años se alcanza la mayoría de edad.', true, 'Desde 2009 (antes era a los 21).'),
    deb('Los contratos con «letra chica» deberían estar prohibidos.'),
    deb('Las leyes deberían escribirse en lenguaje claro para que las entienda cualquiera.'),
    deb('A los 16 años se debería poder firmar cualquier contrato.'),
    deb('Nadie debería poder alegar que no conocía la ley.'),
  ],
  celula: [
    vf('Todas las células tienen núcleo.', false, 'Las bacterias (procariotas) no tienen núcleo definido.'),
    vf('Las plantas liberan oxígeno en la fotosíntesis.', true, 'Toman dióxido de carbono y liberan oxígeno.'),
    vf('Los virus son células.', false, 'No tienen estructura celular: necesitan una célula para reproducirse.'),
    vf('Las células animales tienen pared celular.', false, 'La pared celular es propia de las células vegetales, los hongos y las bacterias.'),
  ],
};

PLANTILLAS.forEach((p) => p.items.push(...(EXTRA[p.id] || [])));

// ── Historias con decisiones (Elegí tu propia aventura) ──
const esc = (id, texto, ...opciones) => ({ id, texto, final: false, opciones: opciones.map(([t, destino, consecuencia = '']) => ({ texto: t, destino, consecuencia })) });
const fin = (id, tipoFinal, texto) => ({ id, texto, final: true, tipoFinal, opciones: [] });

PLANTILLAS.push(
  {
    id: 'historias-cc',
    titulo: 'Historias para decidir: convivencia', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      {
        tipo: 'historia', titulo: 'La foto',
        intro: 'Una foto empieza a circular en el grupo del curso. Cada decisión cambia lo que le pasa a Mica… y a todos.',
        escenas: [
          esc('e1', 'En el grupo de WhatsApp del curso alguien comparte una foto de Mica tomada sin que ella se diera cuenta, en el vestuario. Empiezan los stickers y las risas.',
            ['Me río y la reenvío a otro grupo', 'e2', 'Reenviar también es participar: cada reenvío hace que la foto llegue más lejos.'],
            ['No digo nada y salgo del grupo', 'e3', 'No participar está bien, pero el silencio deja a Mica sola.'],
            ['Escribo en el grupo que la borren, que no está bien', 'e4', 'Frenar la situación en público requiere valentía y suele cambiar el clima del grupo.']),
          esc('e2', 'Al día siguiente la foto circula por toda la escuela. Mica no vino a clase.',
            ['Pienso que no es para tanto: era una broma', 'f_malo', 'Lo que para algunos es una broma, para otra persona puede ser una humillación enorme.'],
            ['Me doy cuenta del daño y hablo con un preceptor', 'e5', 'Pedir ayuda a un adulto no es «buchonear»: es cuidar a alguien.']),
          esc('e3', 'Desde afuera ves que la foto sigue circulando. Mica te escribe: «¿Viste lo que me hicieron?».',
            ['Le digo que no vi nada', 'f_malo', 'Negar lo que pasa aísla todavía más a quien lo sufre.'],
            ['La acompaño y le propongo hablar con un adulto de confianza', 'e5', 'Acompañar a quien sufre la situación es una de las formas más importantes de ayudar.']),
          esc('e4', 'Algunos te apoyan y borran la foto; otros te dicen «amargo». Quien la subió la sigue pasando por privado.',
            ['Le escribo por privado a Mica para acompañarla', 'e5', 'Saber que alguien está de su lado cambia mucho para quien lo sufre.'],
            ['Aviso a la escuela para que intervenga', 'e5', 'Cuando la situación sigue, hace falta que intervengan los adultos.']),
          esc('e5', 'La escuela convoca a las familias y organiza una charla sobre convivencia digital. ¿Qué debería pasar con quien sacó y difundió la foto?',
            ['Que lo echen de la escuela', 'f_neutro', 'Las sanciones existen, pero solo castigar no repara el daño ni evita que vuelva a pasar.'],
            ['Que repare el daño: que pida disculpas y participe de una actividad sobre el tema', 'f_bueno', 'Los acuerdos de convivencia buscan sanciones que reparen y enseñen.']),
          fin('f_malo', 'malo', 'Mica se cambia de escuela. Difundir imágenes de otra persona sin su consentimiento es una forma de violencia, y quienes las reenvían también son parte. Lo que se sube a internet es muy difícil de borrar.'),
          fin('f_neutro', 'neutro', 'El responsable es sancionado, pero en el curso nadie habla de lo que pasó y el clima sigue tenso. ¿Alcanza con castigar?'),
          fin('f_bueno', 'bueno', 'Quien difundió la foto pide disculpas y el curso arma una campaña sobre privacidad y consentimiento. Mica vuelve a sentirse parte. Cuidar la intimidad de los demás es responsabilidad de todos.'),
        ],
      },
      {
        tipo: 'historia', titulo: 'El celular prohibido',
        intro: 'Sos delegado o delegada de tu curso y la escuela toma una decisión que a nadie le gusta. ¿Cómo se hace oír el curso?',
        escenas: [
          esc('e1', 'La dirección anuncia que desde mañana se prohíben los celulares en toda la escuela, también en los recreos. El curso está furioso y te miran a vos, que sos delegado.',
            ['Propongo hacer una asamblea en el curso para discutirlo', 'e2', 'La asamblea es un espacio para que todos opinen antes de decidir qué hacer.'],
            ['Armamos una campaña en redes contra la directora', 'e3', 'Las redes amplifican el enojo, pero atacar a personas suele cerrar el diálogo.'],
            ['No hago nada: total no nos van a escuchar', 'f_nada', 'Cuando no participamos, otros deciden por nosotros.']),
          esc('e2', 'En la asamblea hay opiniones divididas: algunos quieren celulares libres todo el día; otros reconocen que en clase distraen.',
            ['Votamos una propuesta intermedia: celulares solo en los recreos', 'e4', 'Una propuesta concreta y votada tiene más fuerza que una queja.'],
            ['Llevamos todas las opiniones sin ponernos de acuerdo', 'e5', 'Mostrar la diversidad de opiniones está bien, pero sin propuesta es difícil negociar.']),
          esc('e3', 'La publicación se viraliza con insultos a la directora. La escuela suspende las reuniones con los delegados.',
            ['Pedimos disculpas y proponemos volver a hablar', 'e2', 'Reconocer un error también es parte de participar de forma democrática.'],
            ['Seguimos con la campaña', 'f_malo', 'Sin diálogo, el conflicto escala.']),
          esc('e4', 'Presentás la propuesta al centro de estudiantes y a la dirección. La directora dice que lo va a pensar.',
            ['Pedimos que se trate en el Consejo de Convivencia', 'f_bueno', 'Los acuerdos de convivencia se construyen con estudiantes, docentes y familias.'],
            ['Esperamos sin hacer nada más', 'f_neutro', 'Dejar pasar el tiempo suele hacer que el tema se olvide.']),
          esc('e5', 'La dirección recibe muchas opiniones distintas y ninguna propuesta concreta.',
            ['Volvemos al curso a armar una propuesta', 'e4', 'Organizarse lleva tiempo, pero da resultados.'],
            ['Nos damos por vencidos', 'f_neutro', 'Rendirse también es una decisión.']),
          fin('f_bueno', 'bueno', 'En el Consejo de Convivencia se acuerda: celulares guardados en clase y libres en los recreos, con una revisión en tres meses. Participar por los canales democráticos no siempre consigue todo, pero construye acuerdos que se respetan.'),
          fin('f_neutro', 'neutro', 'La prohibición sigue igual y nadie sabe si la van a revisar. Tener razón no alcanza: hace falta organizarse y proponer.'),
          fin('f_malo', 'malo', 'La escuela sanciona a los responsables de la campaña y la prohibición queda firme. Protestar es un derecho, pero sin diálogo ni propuestas el conflicto se agranda.'),
          fin('f_nada', 'malo', 'La prohibición se aplica sin que nadie opine. Cuando no participamos, otros deciden por nosotros.'),
        ],
      },
    ],
  },
  {
    id: 'historias-tyc',
    titulo: 'Historias para decidir: trabajo', materia: 'Trabajo y Ciudadanía', curso: '6° año',
    items: [{
      tipo: 'historia', titulo: 'Mi primer trabajo',
      intro: 'Terminaste la secundaria y necesitás trabajar. Cada decisión tiene consecuencias sobre tus derechos.',
      escenas: [
        esc('e1', 'Tenés 18 años y te ofrecen trabajar en una cafetería del barrio: 8 horas por día, de lunes a sábado. El dueño te dice: «Por ahora te pago en mano, sin recibo; más adelante te registro». Necesitás la plata.',
          ['Acepto: necesito trabajar ya', 'e2', 'Trabajar sin registro es trabajo no registrado («en negro»): no hay aportes jubilatorios, ni obra social, ni ART.'],
          ['Pregunto por qué no me registra desde el primer día', 'e3', 'La ley obliga a registrar al trabajador desde el primer día.'],
          ['Busco otro trabajo, registrado', 'e4', 'Buscar un trabajo registrado puede llevar más tiempo, pero protege tus derechos.']),
        esc('e2', 'Pasan tres meses y seguís sin recibo. Un día te quemás la mano con la máquina de café y tenés que ir a la guardia.',
          ['Pago todo yo y no digo nada, para no perder el trabajo', 'f_malo', 'Sin registro no hay ART que cubra el accidente: los gastos y los días sin trabajar corren por tu cuenta.'],
          ['Le pido al dueño que se haga cargo del accidente', 'e5', 'Aunque no te haya registrado, el empleador es responsable por el accidente.']),
        esc('e3', 'El dueño se enoja: «Si no te gusta, hay diez esperando este puesto».',
          ['Acepto, pero guardo pruebas: mensajes, horarios, fotos', 'e6', 'Mensajes, testigos y registros de horario sirven para probar la relación laboral.'],
          ['Consulto en el sindicato de gastronómicos', 'e7', 'Los sindicatos asesoran sobre derechos laborales.']),
        esc('e4', 'Conseguís trabajo en un supermercado. Te registran desde el primer día. En tu primer recibo ves descuentos que no entendés: jubilación, obra social, sindicato.',
          ['Me enojo: me están sacando plata', 'f_recibo_neutro', 'Los aportes no son un robo: financian tu jubilación y tu obra social.'],
          ['Pregunto qué es cada descuento', 'f_recibo_bueno', 'Entender el recibo de sueldo es parte de conocer tus derechos.']),
        esc('e5', 'El dueño te dice que como no estás registrado «no le corresponde nada» y que si reclamás te despide.',
          ['Me callo para no perder el trabajo', 'f_malo', 'El miedo a perder el trabajo es lo que sostiene la informalidad.'],
          ['Hago la denuncia en el Ministerio de Trabajo', 'f_bueno', 'El Ministerio puede inspeccionar y obligar a registrarte; también podés reclamar por el accidente.']),
        esc('e6', 'Juntaste pruebas durante dos meses. El dueño sigue sin registrarte.',
          ['Hago la denuncia con las pruebas', 'f_bueno', 'Con pruebas, el reclamo es mucho más sólido.'],
          ['Sigo igual: total, cobro', 'f_malo', 'Cada mes sin registro son aportes que no se hacen para tu jubilación.']),
        esc('e7', 'En el sindicato te explican tus derechos: registro desde el primer día, aportes, obra social, ART, vacaciones y aguinaldo. Te ofrecen acompañarte.',
          ['Voy con el delegado a hablar con el dueño', 'f_negociado', 'Reclamar acompañado da más fuerza y más protección.'],
          ['Prefiero no hacer lío y buscar otro trabajo', 'e4', 'También es una opción, pero el problema le queda a quien venga después.']),
        fin('f_malo', 'malo', 'Seguís trabajando sin registro: sin obra social, sin ART, sin aportes para tu jubilación y con el riesgo de que te despidan sin indemnización. El trabajo no registrado afecta a millones de personas; conocer los derechos es el primer paso para cambiarlo.'),
        fin('f_bueno', 'bueno', 'Hiciste la denuncia. Después de una inspección, el dueño tuvo que registrarte y pagarte lo que te debía. Reclamar tiene costos, pero los derechos laborales existen para protegerte.'),
        fin('f_negociado', 'bueno', 'Con el apoyo del sindicato, el dueño aceptó registrarte. Organizarse colectivamente hace más fuerte el reclamo: por eso el artículo 14 bis protege a los gremios.'),
        fin('f_recibo_neutro', 'neutro', 'Te quedaste con la bronca sin entender el recibo. Los aportes financian tu jubilación y tu obra social: preguntar y entender también es un derecho.'),
        fin('f_recibo_bueno', 'bueno', 'La encargada te explica cada descuento: jubilación, obra social y cuota sindical. Ahora sabés leer tu recibo y controlar que te paguen bien.'),
      ],
    }],
  },
);

// ── Secuencias (Ordená la secuencia) ──
const sec = (consigna, ...pasos) => ({ tipo: 'secuencia', consigna, pasos });
const SECUENCIAS = {
  'cc-derechos': [
    sec('Ordená cómo se elige un centro de estudiantes', 'Se convoca a elecciones', 'Se presentan las listas con sus propuestas', 'Las listas hacen campaña', 'Los estudiantes votan en forma secreta', 'Se cuentan los votos', 'Asume la comisión directiva electa'),
    sec('Ordená los pasos de una mediación', 'Las partes aceptan ir a mediación', 'Cada parte cuenta su versión', 'Se identifican los intereses de cada uno', 'Se proponen soluciones posibles', 'Se firma un acuerdo'),
  ],
  'cc-esi': [
    sec('Ordená estas leyes de la más antigua a la más reciente', 'Ley de divorcio vincular', 'Ley de Educación Sexual Integral', 'Ley de matrimonio igualitario', 'Ley de Identidad de Género'),
  ],
  'cc-digital': [
    sec('Ordená qué hacer si te acosan por internet', 'Guardar pruebas (capturas de pantalla)', 'Bloquear a quien acosa', 'Contarle a un adulto de confianza', 'Denunciar el perfil en la plataforma', 'Hacer la denuncia formal'),
    sec('Ordená cómo chequear una noticia antes de compartirla', 'Leer más allá del título', 'Fijarse quién la publica', 'Buscar si otros medios confiables la publicaron', 'Revisar la fecha', 'Decidir si se comparte o no'),
  ],
  pyc: [
    sec('Ordená estos hechos de la historia argentina', 'Se sanciona la Constitución Nacional', 'Ley Sáenz Peña: voto secreto y obligatorio', 'Ley del voto femenino', 'Golpe de Estado de 1976', 'Vuelve la democracia', 'Reforma de la Constitución', 'Voto optativo desde los 16 años'),
    sec('Ordená cómo se sanciona una ley', 'Un legislador presenta el proyecto', 'La cámara de origen lo debate y lo aprueba', 'La cámara revisora lo debate y lo aprueba', 'El Poder Ejecutivo lo promulga', 'Se publica en el Boletín Oficial', 'Entra en vigencia'),
  ],
  tyc: [
    sec('Ordená estas formas de organizar el trabajo, de la más antigua a la más reciente', 'Trabajo artesanal en talleres', 'Manufactura', 'Taylorismo (organización científica del trabajo)', 'Fordismo (cadena de montaje)', 'Toyotismo (producción flexible)'),
    sec('Ordená qué hacer ante un despido sin causa', 'Recibir la comunicación del despido por escrito', 'Pedir la liquidación final', 'Revisar que incluya indemnización, preaviso y vacaciones', 'Si falta algo, reclamar por telegrama laboral', 'Ir a una audiencia de conciliación', 'Si no hay acuerdo, iniciar un juicio laboral'),
  ],
  derecho: [
    sec('Ordená las normas de mayor a menor jerarquía', 'Constitución Nacional y tratados con jerarquía constitucional', 'Otros tratados internacionales', 'Leyes del Congreso', 'Decretos del Poder Ejecutivo', 'Resoluciones de los ministerios', 'Contratos entre particulares'),
    sec('Ordená las etapas de la vida de una ley', 'Iniciativa (presentación del proyecto)', 'Sanción del Congreso', 'Promulgación del Poder Ejecutivo', 'Publicación en el Boletín Oficial', 'Entrada en vigencia'),
  ],
  celula: [
    sec('Ordená las fases de la mitosis', 'Profase', 'Metafase', 'Anafase', 'Telofase'),
    sec('Ordená de menor a mayor nivel de organización', 'Átomo', 'Molécula', 'Célula', 'Tejido', 'Órgano', 'Sistema de órganos', 'Organismo'),
  ],
};
PLANTILLAS.forEach((p) => p.items.push(...(SECUENCIAS[p.id] || [])));

PLANTILLAS.push(...GENERALES, ...MATERIAS);
