// Bancos listos para usar. El docente los agrega a «Mis bancos» con un toque y
// después los puede editar como cualquier otro.
//
// Revisá números de ley y artículos antes de usarlos: están escritos para
// secundaria de la provincia de Buenos Aires, pero conviene chequearlos con tu planificación.

const t = (termino, definicion) => ({ tipo: 'termino', termino, definicion });
const p = (pregunta, correcta, ...incorrectas) => ({ tipo: 'pregunta', pregunta, correcta, incorrectas });
const par = (a, b) => ({ tipo: 'par', a, b });
const enc = (pregunta, ...respuestas) => ({
  tipo: 'encuesta', pregunta,
  respuestas: respuestas.map((r) => { const [texto, pts] = r.split('='); return { texto: texto.trim(), puntos: Number(pts) }; }),
});

export const PLANTILLAS = [
  {
    id: 'cc-derechos',
    titulo: 'Derechos y participación', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      t('adolescencia', 'Etapa de la vida entre la niñez y la adultez, en la que se consolidan la identidad y la autonomía'),
      t('asamblea', 'Reunión en la que un grupo delibera y toma decisiones en conjunto'),
      t('bien común', 'Lo que beneficia a todas las personas de una comunidad y no solo a algunas'),
      t('centro de estudiantes', 'Organización elegida por voto que representa a los alumnos de una escuela'),
      t('ciudadanía', 'Condición de quien forma parte de una comunidad política y ejerce en ella derechos y obligaciones'),
      t('Convención sobre los Derechos del Niño / CDN', 'Tratado internacional de 1989 que reconoce a niñas, niños y adolescentes como sujetos de derecho'),
      t('delegado / delegada', 'Estudiante elegido por su curso para representarlo'),
      t('discriminación', 'Trato desigual o excluyente hacia una persona por su origen, género, religión u otra condición'),
      t('estereotipo', 'Imagen simplificada y generalizada que se atribuye a todo un grupo de personas'),
      t('identidad', 'Conjunto de rasgos que hacen que una persona sea quien es y se reconozca como tal'),
      t('igualdad', 'Principio según el cual todas las personas tienen los mismos derechos'),
      t('interés superior del niño', 'Principio que obliga a priorizar el bienestar de niñas, niños y adolescentes en toda decisión que los afecte'),
      t('ley', 'Norma general y obligatoria dictada por el Poder Legislativo'),
      t('mediación', 'Forma de resolver un conflicto con ayuda de una tercera persona neutral'),
      t('norma', 'Regla que indica cómo se debe actuar en una comunidad'),
      t('participación', 'Tomar parte activa en las decisiones y los asuntos de una comunidad'),
      t('prejuicio', 'Opinión, generalmente negativa, que se forma sin conocer a la persona o la situación'),
      t('responsabilidad', 'Capacidad de responder por los propios actos y sus consecuencias'),
      t('sujeto de derecho', 'Persona a la que la ley le reconoce derechos y la posibilidad de exigirlos'),
      t('tolerancia', 'Respeto por las ideas y prácticas de los demás aunque sean distintas de las propias'),
      t('voto', 'Forma de expresar una elección en una votación'),
      p('¿Qué tratado reconoce a niñas, niños y adolescentes como sujetos de derecho?', 'la Convención sobre los Derechos del Niño', 'la Constitución de 1853', 'el Acta de la Independencia', 'el Código Penal'),
      p('¿En qué año se aprobó la Convención sobre los Derechos del Niño?', '1989', '1810', '1994', '2005'),
      p('¿Qué jerarquía tiene la Convención sobre los Derechos del Niño en Argentina desde 1994?', 'jerarquía constitucional', 'la de una ley provincial', 'la de un decreto', 'ninguna, es solo una recomendación'),
      p('¿Qué ley nacional establece la protección integral de los derechos de niñas, niños y adolescentes?', 'Ley 26.061', 'Ley 26.150', 'Ley 20.744', 'Ley 24.240'),
      p('¿Desde qué edad se puede votar en Argentina?', '16 años', '14 años', '18 años', '21 años'),
      p('¿Qué organización representa a los estudiantes dentro de la escuela?', 'el centro de estudiantes', 'la cooperadora', 'el equipo directivo', 'la inspección'),
      p('Tratar de manera desigual a alguien por su origen es…', 'discriminación', 'tolerancia', 'mediación', 'participación'),
      p('Decir que «todas las chicas son malas para las matemáticas» es un ejemplo de…', 'estereotipo', 'derecho', 'norma', 'mediación'),
      p('¿Qué hace una persona mediadora en un conflicto?', 'ayuda a que las partes lleguen a un acuerdo', 'decide quién tiene razón', 'sanciona al culpable', 'defiende a una de las partes'),
      p('Si a un chico no lo dejan inscribirse en la escuela, ¿qué derecho se vulnera?', 'el derecho a la educación', 'el derecho al voto', 'el derecho de huelga', 'el derecho de propiedad'),
      par('prejuicio', 'estereotipo'),
      par('derecho', 'obligación'),
      par('igualdad', 'equidad'),
      par('norma', 'ley'),
      par('ciudadano', 'habitante'),
      par('discriminación', 'exclusión'),
      par('mediación', 'negociación'),
      par('tolerancia', 'respeto'),
      enc('Nombrá un derecho de los adolescentes', 'educación = 30', 'salud = 20', 'identidad / nombre = 15', 'jugar / recreación / esparcimiento = 12', 'opinar / libertad de expresión / expresarse = 10', 'ser escuchado / ser oído = 8'),
      enc('Una forma de participar en la escuela', 'votar / elecciones = 30', 'centro de estudiantes = 25', 'ser delegado / delegada = 15', 'asambleas = 12', 'proponer ideas / propuestas = 10', 'actos escolares = 8'),
      enc('Algo que hace un centro de estudiantes', 'organizar actividades / eventos = 30', 'representar a los alumnos = 25', 'hacer reclamos = 15', 'recaudar fondos / rifas = 10', 'organizar torneos = 10', 'llevar propuestas a la dirección = 10'),
    ],
  },
  {
    id: 'cc-esi',
    titulo: 'ESI: sexualidad y género', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      t('afectividad', 'Dimensión de la sexualidad ligada a las emociones, los sentimientos y los vínculos'),
      t('buen trato', 'Forma de relacionarse basada en el respeto y el cuidado mutuo'),
      t('consentimiento', 'Acuerdo libre y claro para hacer algo, que se puede retirar en cualquier momento'),
      t('cuidado', 'Hábitos y decisiones para proteger la salud y el bienestar propio y de los demás'),
      t('diversidad', 'Variedad de formas de ser, sentir, vivir y expresarse que existen en una sociedad'),
      t('ESI / educación sexual integral', 'Derecho de los estudiantes a recibir educación sexual en todas las escuelas, establecido por la Ley 26.150'),
      t('equidad de género', 'Igualdad de oportunidades y de trato entre personas de distintos géneros'),
      t('femicidio', 'Asesinato de una mujer por razones de género'),
      t('género', 'Construcción social y cultural sobre los roles asignados a las personas según su sexo'),
      t('identidad de género', 'Vivencia interna de cada persona sobre su género, que puede coincidir o no con el sexo asignado al nacer'),
      t('intimidad', 'Espacio personal que cada persona tiene derecho a proteger de los demás'),
      t('Ley Micaela', 'Ley que establece la capacitación obligatoria en género para quienes trabajan en el Estado'),
      t('machismo', 'Conjunto de actitudes que consideran a los varones superiores a las mujeres'),
      t('matrimonio igualitario', 'Ley de 2010 que permite casarse a personas del mismo sexo'),
      t('Ni Una Menos', 'Movimiento surgido en 2015 contra la violencia hacia las mujeres'),
      t('orientación sexual', 'Atracción afectiva o sexual que una persona siente hacia otras'),
      t('patriarcado', 'Organización social en la que predomina el poder de los varones'),
      t('respeto', 'Consideración y valoración de las demás personas y de sus decisiones'),
      t('sexualidad', 'Dimensión de la persona que incluye el cuerpo, las emociones, los vínculos y la identidad'),
      t('violencia de género', 'Toda conducta que daña a una persona por razones de género'),
      p('¿Qué ley creó el Programa Nacional de Educación Sexual Integral?', 'Ley 26.150', 'Ley 26.061', 'Ley 26.743', 'Ley 27.499'),
      p('¿En qué escuelas es obligatoria la ESI?', 'en todas, públicas y privadas', 'solo en las públicas', 'solo en las secundarias', 'solo si las familias lo piden'),
      p('¿Cuál de estos es uno de los ejes de la ESI?', 'valorar la afectividad', 'aprobar exámenes', 'competir en deportes', 'elegir una carrera'),
      p('¿En qué año se sancionó la Ley de Identidad de Género?', '2012', '1994', '2006', '2020'),
      p('¿En qué año se aprobó el matrimonio igualitario en Argentina?', '2010', '2015', '2002', '1987'),
      p('¿Qué establece la Ley Micaela?', 'capacitación obligatoria en género para quienes trabajan en el Estado', 'ESI en todas las escuelas', 'licencias por nacimiento', 'el cupo laboral trans'),
      p('¿Qué movimiento surgió en 2015 contra la violencia hacia las mujeres?', 'Ni Una Menos', 'Madres de Plaza de Mayo', 'el Mayo Francés', 'la Primavera Árabe'),
      p('¿Qué característica tiene el consentimiento?', 'se puede retirar en cualquier momento', 'vale para siempre', 'se da una sola vez', 'lo puede dar otra persona'),
      p('Revisarle el celular a la pareja sin permiso es una señal de…', 'control en la pareja', 'cuidado', 'confianza', 'respeto'),
      p('¿Qué es el género?', 'una construcción social y cultural', 'una característica biológica', 'una ley', 'un documento'),
      par('sexo', 'género'),
      par('identidad de género', 'orientación sexual'),
      par('igualdad', 'equidad'),
      par('machismo', 'patriarcado'),
      par('femicidio', 'violencia de género'),
      par('intimidad', 'privacidad'),
      par('afectividad', 'sexualidad'),
      par('consentimiento', 'permiso'),
      enc('Un estereotipo de género que escuchaste', 'los hombres no lloran = 30', 'las mujeres son débiles / sexo débil = 20', 'el rosa es de nena / colores de nena = 15', 'las mujeres cocinan / tareas de la casa = 15', 'el fútbol es de varones = 12', 'las mujeres manejan mal = 8'),
      enc('Una señal de noviazgo violento', 'celos / celos excesivos = 30', 'revisar el celular = 25', 'prohibir salir con amigos = 18', 'insultos / gritos = 12', 'controlar la ropa = 10', 'golpes / empujones = 5'),
      enc('Algo que tiene que tener una relación sana', 'respeto = 30', 'confianza = 25', 'comunicación / diálogo = 20', 'libertad = 10', 'amor / cariño = 10', 'consentimiento = 5'),
    ],
  },
  {
    id: 'cc-digital',
    titulo: 'Comunicación, TIC y convivencia digital', materia: 'Construcción de Ciudadanía', curso: '1° a 3° año',
    items: [
      t('algoritmo', 'Instrucciones que usan las plataformas para decidir qué contenido mostrarte'),
      t('burbuja de filtro', 'Efecto por el que las redes te muestran solo contenidos parecidos a los que ya te gustan'),
      t('ciberbullying / ciberacoso', 'Acoso entre pares a través de redes sociales, mensajes o juegos en línea'),
      t('contraseña', 'Clave secreta que protege una cuenta'),
      t('datos personales', 'Información que identifica a una persona, como su nombre, su DNI o su dirección'),
      t('deepfake', 'Video o audio falso hecho con inteligencia artificial que imita a una persona real'),
      t('desinformación', 'Información falsa que se difunde a propósito para engañar'),
      t('fake news / noticia falsa', 'Noticia inventada o manipulada que se presenta como si fuera verdadera'),
      t('grooming', 'Acoso de una persona adulta a un menor por internet con fines sexuales'),
      t('huella digital', 'Rastro de información que dejamos al usar internet'),
      t('influencer', 'Persona con muchos seguidores que influye en las opiniones y el consumo de otros'),
      t('inteligencia artificial / IA', 'Sistemas informáticos capaces de hacer tareas que parecen requerir inteligencia humana'),
      t('medios de comunicación', 'Canales que llevan información a gran cantidad de personas, como la TV, la radio o los diarios'),
      t('netiqueta', 'Normas de buena conducta en internet'),
      t('phishing', 'Engaño para robar contraseñas o datos haciéndose pasar por otra persona o empresa'),
      t('privacidad', 'Derecho a decidir qué información propia se comparte y con quién'),
      t('sexting', 'Envío de fotos o mensajes de contenido sexual por medios digitales'),
      t('troll', 'Usuario que publica mensajes para provocar o generar peleas'),
      t('verificación / chequeo', 'Comprobar si una información es verdadera consultando fuentes confiables'),
      t('viralización', 'Difusión masiva y muy rápida de un contenido en internet'),
      p('¿Qué es el grooming?', 'el acoso de un adulto a un menor por internet', 'un tipo de virus', 'una red social', 'una pelea entre compañeros'),
      p('¿Qué ley incorporó el grooming como delito al Código Penal?', 'Ley 26.904', 'Ley 26.150', 'Ley 25.326', 'Ley 20.744'),
      p('¿Qué ley protege los datos personales en Argentina?', 'Ley 25.326', 'Ley 26.904', 'Ley 26.061', 'Ley 24.240'),
      p('¿Qué conviene hacer antes de compartir una noticia?', 'verificarla en fuentes confiables', 'compartirla rápido', 'mirar cuántos likes tiene', 'preguntar en un grupo de WhatsApp'),
      p('¿Qué es la huella digital?', 'el rastro que dejamos en internet', 'la huella del dedo para desbloquear el celular', 'una contraseña', 'una aplicación'),
      p('Si alguien te acosa por redes, ¿qué conviene hacer?', 'guardar pruebas y contárselo a un adulto de confianza', 'borrar todo', 'responder con insultos', 'no decirle a nadie'),
      p('Un mail que pide tu contraseña haciéndose pasar por tu banco es…', 'phishing', 'netiqueta', 'viralización', 'un algoritmo'),
      p('¿Qué es una burbuja de filtro?', 'que las redes te muestren solo lo que ya pensás', 'un filtro para fotos', 'un antivirus', 'un grupo privado'),
      p('¿Cuál es la contraseña más segura?', 'una frase larga con números y símbolos', 'tu fecha de nacimiento', '123456', 'tu nombre'),
      p('¿Qué es un deepfake?', 'un video falso hecho con inteligencia artificial', 'una red social', 'un tipo de meme', 'una transmisión en vivo'),
      par('bullying', 'ciberbullying'),
      par('grooming', 'sexting'),
      par('fake news', 'rumor'),
      par('phishing', 'hackeo'),
      par('algoritmo', 'burbuja de filtro'),
      par('influencer', 'celebridad'),
      par('privacidad', 'intimidad'),
      par('troll', 'hater'),
      enc('Una red social o app que usás todos los días', 'Instagram = 30', 'TikTok = 28', 'WhatsApp = 20', 'YouTube = 12', 'Discord = 5', 'X / Twitter = 5'),
      enc('Un peligro de internet', 'grooming = 25', 'estafas / phishing = 20', 'ciberbullying / acoso = 20', 'hackeo / robo de cuentas = 15', 'fake news / noticias falsas = 12', 'adicción = 8'),
      enc('Algo que no hay que compartir en redes', 'dirección / dónde vivís = 30', 'contraseñas = 25', 'fotos íntimas = 20', 'DNI / documento = 10', 'número de teléfono = 10', 'ubicación en tiempo real = 5'),
    ],
  },
  {
    id: 'pyc',
    titulo: 'Estado, democracia y derechos', materia: 'Política y Ciudadanía', curso: '5° año',
    items: [
      t('amparo', 'Acción judicial rápida contra actos que lesionan derechos reconocidos por la Constitución (art. 43)'),
      t('autoritarismo', 'Forma de ejercer el poder sin respetar límites ni libertades'),
      t('Constitución Nacional', 'Ley suprema del país, que organiza el Estado y reconoce derechos y garantías'),
      t('consulta popular', 'Mecanismo por el que el Congreso somete un proyecto de ley al voto de la ciudadanía (art. 40)'),
      t('democracia', 'Forma de gobierno en la que el poder reside en el pueblo'),
      t('división de poderes', 'Separación del poder del Estado en Ejecutivo, Legislativo y Judicial'),
      t('Estado', 'Organización política que ejerce el poder sobre una población en un territorio'),
      t('federalismo', 'Forma de organización en la que el poder se reparte entre el Estado nacional y las provincias'),
      t('gobierno', 'Conjunto de personas que ejercen temporalmente el poder del Estado'),
      t('hábeas corpus', 'Acción judicial que protege a una persona detenida de manera ilegal'),
      t('iniciativa popular', 'Derecho de la ciudadanía a presentar proyectos de ley en la Cámara de Diputados (art. 39)'),
      t('juicio político', 'Procedimiento del Congreso para destituir al presidente, a ministros o a jueces de la Corte'),
      t('legitimidad', 'Aceptación de un poder por parte de la sociedad como justo o válido'),
      t('Ley Sáenz Peña', 'Ley de 1912 que estableció el voto secreto y obligatorio para los varones'),
      t('Nunca Más', 'Informe de la CONADEP de 1984 sobre los crímenes de la última dictadura'),
      t('partido político', 'Organización que busca acceder al gobierno y a través de la cual se postulan candidatos'),
      t('poder', 'Capacidad de influir en las decisiones y la conducta de otras personas'),
      t('república', 'Forma de gobierno con división de poderes, elecciones periódicas y publicidad de los actos'),
      t('soberanía popular', 'Principio según el cual el poder emana del pueblo'),
      t('sufragio', 'Derecho a votar y a ser votado'),
      t('terrorismo de Estado', 'Uso ilegal y sistemático de la violencia por parte del propio Estado contra la población'),
      t('hábeas data', 'Acción judicial para conocer y corregir los datos personales que figuran en registros'),
      p('¿Qué estableció la Ley Sáenz Peña de 1912?', 'el voto secreto y obligatorio para los varones', 'el voto femenino', 'el voto desde los 16 años', 'la reforma de la Constitución'),
      p('¿En qué año votaron las mujeres por primera vez en una elección nacional?', '1951', '1912', '1983', '1994'),
      p('¿En qué año se reformó la Constitución y se dio jerarquía constitucional a los tratados de derechos humanos?', '1994', '1853', '1983', '1949'),
      p('¿Qué artículo de la Constitución habilita la iniciativa popular?', 'el 39', 'el 14 bis', 'el 75', 'el 1'),
      p('¿Cuál de estos NO es un poder del Estado?', 'el Poder Electoral', 'el Poder Ejecutivo', 'el Poder Legislativo', 'el Poder Judicial'),
      p('Detienen a una persona sin orden de un juez. ¿Qué acción corresponde?', 'hábeas corpus', 'hábeas data', 'juicio político', 'iniciativa popular'),
      p('¿Qué organismo elaboró el informe «Nunca Más»?', 'la CONADEP', 'la Corte Suprema', 'el Congreso', 'la ONU'),
      p('¿Qué forma de gobierno adopta la Constitución en su artículo 1?', 'representativa, republicana y federal', 'monárquica', 'parlamentaria', 'unitaria'),
      p('¿En qué año volvió la democracia a la Argentina tras la última dictadura?', '1983', '1976', '1989', '1973'),
      p('¿Qué dice el artículo 22 de la Constitución?', 'el pueblo no delibera ni gobierna sino por medio de sus representantes', 'todos los habitantes son iguales ante la ley', 'nadie puede ser penado sin juicio previo', 'el gobierno federal sostiene el culto católico'),
      par('Estado', 'gobierno'),
      par('legalidad', 'legitimidad'),
      par('poder', 'autoridad'),
      par('amparo', 'hábeas corpus'),
      par('hábeas corpus', 'hábeas data'),
      par('democracia directa', 'democracia representativa'),
      par('iniciativa popular', 'consulta popular'),
      par('república', 'democracia'),
      enc('Un derecho que garantiza la democracia', 'votar / voto / sufragio = 30', 'libertad de expresión = 25', 'igualdad ante la ley / igualdad = 15', 'protestar / manifestarse = 12', 'educación = 10', 'libertad de prensa = 8'),
      enc('Algo que hace el Congreso', 'hacer leyes / sancionar leyes = 40', 'aprobar el presupuesto = 20', 'juicio político = 15', 'debatir = 10', 'aprobar tratados = 10', 'controlar al Poder Ejecutivo = 5'),
      enc('Una forma de participar en política', 'votar = 35', 'militar en un partido = 20', 'marchas / manifestaciones = 15', 'centro de estudiantes = 12', 'firmar petitorios / peticiones = 10', 'ser candidato = 8'),
    ],
  },
  {
    id: 'escape-voto',
    titulo: 'Escape: El voto robado', materia: 'Política y Ciudadanía', curso: '4° a 6° año',
    items: [{
      tipo: 'escape',
      titulo: 'El voto robado',
      minutos: 30,
      intro: 'Faltan pocas horas para la elección del centro de estudiantes y alguien se llevó la urna con todos los votos. Antes de desaparecer, dejó una serie de candados con acertijos sobre la democracia. Tienen 30 minutos para abrirlos, encontrar la urna y salvar la elección. Pueden usar la Constitución Nacional.',
      final: '¡Encontraron la urna! Los votos están a salvo y la elección se puede hacer. Sin voto universal, igual, secreto y obligatorio no hay democracia… y sin participación, tampoco.',
      candados: [
        {
          titulo: 'La puerta de preceptoría', tipo: 'numero', respuesta: '1912',
          desafio: 'En la puerta hay un papel: «La clave es el año de la ley que hizo que el voto fuera secreto y obligatorio para los varones. Antes de esa ley, se votaba cantando el voto en voz alta».',
          pistas: ['La ley lleva el nombre del presidente que la impulsó: Roque Sáenz Peña.', 'Fue dos años antes de que empezara la Primera Guerra Mundial (1914).'],
        },
        {
          titulo: 'El cuaderno de actas', tipo: 'palabra', respuesta: 'representantes',
          desafio: 'En el cuaderno falta una palabra: «El pueblo no delibera ni gobierna sino por medio de sus ______ y autoridades creadas por esta Constitución». La palabra que falta abre el candado.',
          pistas: ['Es el artículo 22 de la Constitución Nacional.', 'Son las personas que elegimos con el voto: diputados, senadores, presidente…'],
        },
        {
          titulo: 'El armario de la dirección', tipo: 'direccion', respuesta: 'arriba,abajo,derecha,arriba',
          desafio: 'En el armario hay un cartel: «Cada poder tiene su flecha: el Legislativo ↑, el Ejecutivo → y el Judicial ↓». Debajo, el ladrón escribió: «Primero el que hace las leyes, después el que resuelve los conflictos cuando no se cumplen, luego el que las pone en práctica y al final, otra vez, el que las hace».',
          pistas: ['Son 4 flechas. La primera y la última son iguales.', 'Hacer leyes: Legislativo. Resolver conflictos: Judicial. Poner en práctica: Ejecutivo.'],
        },
        {
          titulo: 'La caja fuerte', tipo: 'numero', respuesta: '117',
          desafio: 'La caja fuerte pide un número de 3 cifras. Una nota dice: «Sumá los números de los artículos de la Constitución que tratan sobre los partidos políticos, la iniciativa popular y la consulta popular».',
          pistas: ['Los tres artículos están seguidos, justo después del que habla del sufragio (el 37).', 'Partidos políticos: 38. Iniciativa popular: 39. Consulta popular: 40.'],
        },
        {
          titulo: 'El candado de colores', tipo: 'color', respuesta: 'rojo,azul,verde,amarillo',
          desafio: 'El artículo 37 dice que el sufragio es universal (azul), igual (verde), secreto (rojo) y obligatorio (amarillo). El ladrón los desordenó: el código empieza por el que asegura que nadie sepa a quién votaste, sigue el que dice que todos pueden votar, después el que hace que cada voto valga lo mismo y termina con el que nos obliga a votar.',
          pistas: ['Son 4 colores, uno por cada característica del voto.', 'Secreto → universal → igual → obligatorio.'],
        },
        {
          titulo: 'La urna', tipo: 'palabra', respuesta: 'democracia',
          desafio: 'Encontraron la urna, pero tiene un último candado: «La palabra es la forma de gobierno en la que el poder reside en el pueblo. Argentina la recuperó en 1983 y la tenemos que cuidar entre todos».',
          pistas: ['Viene del griego: demos (pueblo) y kratos (poder).', 'Tiene 10 letras y empieza con D.'],
        },
      ],
    }],
  },
  {
    id: 'tyc',
    titulo: 'Derechos laborales y mundo del trabajo', materia: 'Trabajo y Ciudadanía', curso: '6° año',
    items: [
      t('aguinaldo / SAC', 'Sueldo anual complementario que se paga en dos cuotas, en junio y en diciembre'),
      t('aportes', 'Parte del salario que se descuenta para la jubilación y la obra social'),
      t('ART / aseguradora de riesgos del trabajo', 'Aseguradora que cubre los accidentes y las enfermedades laborales'),
      t('convenio colectivo', 'Acuerdo entre sindicatos y empleadores que fija salarios y condiciones de trabajo de una actividad'),
      t('cooperativa', 'Empresa de propiedad colectiva en la que los socios deciden de forma democrática'),
      t('desocupación / desempleo', 'Situación de quienes buscan trabajo activamente y no lo consiguen'),
      t('economía social', 'Formas de producción basadas en la cooperación y no en el lucro'),
      t('empleo', 'Trabajo que se hace a cambio de un salario, en relación de dependencia'),
      t('flexibilización laboral', 'Reducción de las protecciones legales del trabajador para abaratar costos'),
      t('fordismo', 'Modelo de producción en cadena de montaje, en serie y a gran escala'),
      t('huelga / paro', 'Medida de fuerza en la que los trabajadores dejan de trabajar para reclamar'),
      t('indemnización', 'Pago que recibe el trabajador cuando lo despiden sin causa justificada'),
      t('informalidad / trabajo no registrado', 'Trabajo sin registrar, sin aportes ni protección legal (trabajo «en negro»)'),
      t('jubilación', 'Ingreso que recibe una persona al retirarse de la vida laboral'),
      t('licencia', 'Permiso para faltar al trabajo sin perder el salario, por ejemplo por enfermedad o nacimiento'),
      t('monotributo', 'Régimen simplificado de impuestos para trabajadores independientes'),
      t('obra social', 'Entidad que brinda cobertura de salud a los trabajadores y sus familias'),
      t('paritarias', 'Negociaciones periódicas entre sindicatos y empleadores para fijar salarios'),
      t('recibo de sueldo', 'Documento que detalla el salario y los descuentos del trabajador'),
      t('salario mínimo, vital y móvil', 'Menor remuneración que puede cobrar un trabajador en relación de dependencia'),
      t('sindicato', 'Organización que agrupa a trabajadores para defender sus derechos'),
      t('tareas de cuidado', 'Trabajo de atender a niños, personas mayores o enfermas y sostener el hogar, muchas veces sin paga'),
      t('toyotismo', 'Modelo de producción flexible y «justo a tiempo» surgido en Japón'),
      t('vacaciones', 'Descanso anual pago al que tiene derecho todo trabajador registrado'),
      t('trabajo decente', 'Concepto de la OIT: trabajo productivo, con ingreso justo, protección social y derechos'),
      p('¿Qué artículo de la Constitución reconoce los derechos del trabajador y el derecho de huelga?', 'el 14 bis', 'el 16', 'el 22', 'el 75'),
      p('¿Qué ley regula el trabajo en relación de dependencia?', 'la Ley de Contrato de Trabajo (20.744)', 'la Ley de Defensa del Consumidor', 'la Ley de ESI', 'la Ley de Protección Integral'),
      p('¿Desde qué edad se permite trabajar en Argentina?', '16 años', '14 años', '12 años', '18 años'),
      p('¿Cuándo se paga el aguinaldo?', 'en junio y en diciembre', 'en enero', 'cada tres meses', 'cuando lo decide el empleador'),
      p('¿Qué organización internacional promueve el «trabajo decente»?', 'la OIT', 'la FIFA', 'la OTAN', 'el FMI'),
      p('Trabajar sin recibo de sueldo ni aportes es…', 'trabajo no registrado', 'trabajo decente', 'monotributo', 'una paritaria'),
      p('¿Qué cubre la ART?', 'los accidentes y las enfermedades laborales', 'las vacaciones', 'el aguinaldo', 'la jubilación'),
      p('¿Qué es una paritaria?', 'una negociación salarial entre sindicatos y empleadores', 'una huelga', 'un despido', 'un impuesto'),
      p('El modelo de producción en cadena de montaje se conoce como…', 'fordismo', 'toyotismo', 'cooperativismo', 'feudalismo'),
      p('¿Qué organismo mide la desocupación en Argentina?', 'el INDEC', 'el Banco Central', 'la ANSES', 'la Corte Suprema'),
      par('trabajo', 'empleo'),
      par('desocupación', 'subocupación'),
      par('sindicato', 'cooperativa'),
      par('fordismo', 'toyotismo'),
      par('trabajo informal', 'trabajo precario'),
      par('jubilación', 'pensión'),
      par('convenio colectivo', 'paritaria'),
      par('obra social', 'ART'),
      enc('Un derecho del trabajador', 'vacaciones = 25', 'aguinaldo = 20', 'salario / sueldo = 20', 'obra social = 12', 'jubilación / aportes = 10', 'licencias = 8', 'indemnización = 5'),
      enc('Un trabajo que te gustaría tener', 'médico / médica = 20', 'docente / profesor / profesora = 18', 'programador / programadora = 15', 'abogado / abogada = 12', 'futbolista = 12', 'psicólogo / psicóloga = 10', 'influencer / streamer = 8'),
      enc('Algo que aparece en un recibo de sueldo', 'sueldo básico / salario = 30', 'descuentos = 20', 'aportes jubilatorios / jubilación = 15', 'obra social = 15', 'antigüedad = 10', 'horas extra = 10'),
    ],
  },
  {
    id: 'derecho',
    titulo: 'Introducción al derecho', materia: 'Derecho', curso: '5° año · Economía y Administración',
    items: [
      t('acto jurídico', 'Acto voluntario y lícito cuyo fin es crear, modificar o extinguir relaciones jurídicas'),
      t('capacidad de derecho', 'Aptitud de toda persona para ser titular de derechos y deberes'),
      t('capacidad de ejercicio', 'Aptitud para ejercer por sí mismo los propios derechos'),
      t('Código Civil y Comercial', 'Código vigente desde 2015 que unificó el derecho civil y el comercial'),
      t('contrato', 'Acuerdo de dos o más partes para crear, modificar o extinguir relaciones patrimoniales'),
      t('costumbre', 'Fuente del derecho formada por prácticas repetidas que la comunidad considera obligatorias'),
      t('doctrina', 'Opiniones y estudios de los especialistas en derecho'),
      t('domicilio', 'Atributo de la persona: lugar donde reside de forma habitual'),
      t('fuentes del derecho', 'Origen de las normas jurídicas: la ley, la costumbre, la jurisprudencia y la doctrina'),
      t('hecho jurídico', 'Acontecimiento que produce el nacimiento, la modificación o la extinción de relaciones jurídicas'),
      t('jurisprudencia', 'Conjunto de fallos de los tribunales que resuelven casos parecidos de la misma manera'),
      t('ley', 'Norma general y obligatoria dictada por el Poder Legislativo'),
      t('nombre', 'Atributo de la persona formado por el prenombre y el apellido'),
      t('norma jurídica', 'Regla de conducta obligatoria cuyo incumplimiento tiene una sanción'),
      t('obligación', 'Relación jurídica en la que el deudor debe cumplir una prestación a favor del acreedor'),
      t('patrimonio', 'Conjunto de bienes con valor económico de una persona'),
      t('persona jurídica', 'Ente al que la ley le reconoce aptitud para adquirir derechos y contraer obligaciones, como una sociedad'),
      t('prescripción', 'Adquisición o pérdida de derechos por el paso del tiempo'),
      t('sanción', 'Consecuencia que se aplica a quien no cumple una norma'),
      t('sociedad anónima', 'Tipo de sociedad cuyo capital se divide en acciones'),
      t('vigencia', 'Período durante el cual una norma es obligatoria'),
      t('Kelsen / pirámide jurídica', 'Jurista que representó el orden jerárquico de las normas con una pirámide'),
      p('Si una ley no indica otra fecha, ¿desde cuándo rige?', 'después del octavo día de su publicación oficial', 'desde que se sanciona', 'al mes de publicada', 'al año de publicada'),
      p('¿A qué edad se alcanza la mayoría de edad en Argentina?', '18 años', '21 años', '16 años', '13 años'),
      p('Según el Código Civil y Comercial, ¿desde qué edad una persona es adolescente?', '13 años', '12 años', '16 años', '15 años'),
      p('¿En qué año entró en vigencia el Código Civil y Comercial actual?', '2015', '1871', '1994', '2010'),
      p('¿Qué norma está en la cima de la pirámide jurídica argentina?', 'la Constitución Nacional', 'las leyes', 'los decretos', 'las ordenanzas municipales'),
      p('Los fallos repetidos de los tribunales sobre casos parecidos se llaman…', 'jurisprudencia', 'doctrina', 'costumbre', 'legislación'),
      p('¿Cuál de estas es una persona jurídica?', 'una sociedad anónima', 'un recién nacido', 'un juez', 'un adolescente'),
      p('¿Qué ley protege los derechos de los consumidores?', 'Ley 24.240', 'Ley 20.744', 'Ley 26.994', 'Ley 25.326'),
      p('¿Cuál NO es un atributo de la persona?', 'la profesión', 'el nombre', 'el domicilio', 'la capacidad'),
      p('Comprar un celular en un comercio es un ejemplo de…', 'contrato', 'hecho jurídico natural', 'delito', 'costumbre'),
      par('persona humana', 'persona jurídica'),
      par('capacidad de derecho', 'capacidad de ejercicio'),
      par('derecho objetivo', 'derecho subjetivo'),
      par('hecho jurídico', 'acto jurídico'),
      par('doctrina', 'jurisprudencia'),
      par('ley', 'decreto'),
      par('sociedad anónima', 'SRL'),
      par('derecho público', 'derecho privado'),
      enc('Un atributo de la persona', 'nombre = 30', 'domicilio = 25', 'capacidad = 15', 'estado civil / estado = 12', 'patrimonio = 10', 'nacionalidad = 8'),
      enc('Un contrato que hacemos en la vida cotidiana', 'compraventa / comprar = 35', 'alquiler / locación = 25', 'trabajo / contrato de trabajo = 15', 'transporte / viajar en colectivo = 10', 'seguro = 8', 'préstamo = 7'),
      enc('Una fuente del derecho', 'ley = 40', 'costumbre = 25', 'jurisprudencia = 20', 'doctrina = 15'),
    ],
  },
  {
    id: 'celula',
    titulo: 'La célula (ejemplo)', materia: 'Biología', curso: '2° año',
    items: [
      t('ADN', 'Molécula que contiene la información genética'),
      t('bacteria', 'Organismo unicelular procariota'),
      t('cloroplasto', 'Orgánulo donde ocurre la fotosíntesis'),
      t('difusión', 'Paso de sustancias desde donde hay más concentración hacia donde hay menos'),
      t('eucariota', 'Célula que tiene un núcleo definido'),
      t('fotosíntesis', 'Proceso por el cual las plantas fabrican su alimento usando la luz'),
      t('glucosa', 'Azúcar que las células usan como principal fuente de energía'),
      t('hongo', 'Reino al que pertenecen las levaduras y el moho'),
      t('lisosoma', 'Orgánulo que digiere sustancias dentro de la célula'),
      t('mitocondria', 'Orgánulo donde se produce la energía de la célula'),
      t('núcleo', 'Parte de la célula que guarda el material genético'),
      t('ósmosis', 'Paso de agua a través de una membrana semipermeable'),
      t('pared celular', 'Capa rígida que rodea a la célula vegetal'),
      t('ribosoma', 'Estructura donde se fabrican las proteínas'),
      t('tejido', 'Conjunto de células parecidas que cumplen una misma función'),
      t('vacuola', 'Orgánulo que almacena agua y otras sustancias'),
      t('citoplasma', 'Medio acuoso donde flotan los orgánulos de la célula'),
      p('¿Qué orgánulo produce la energía de la célula?', 'mitocondria', 'ribosoma', 'vacuola', 'núcleo'),
      p('¿Cuál de estos organismos NO tiene núcleo definido?', 'una bacteria', 'un hongo', 'una planta', 'un animal'),
      p('¿Qué estructura tienen las células vegetales pero no las animales?', 'pared celular', 'membrana plasmática', 'citoplasma', 'ribosomas'),
      p('¿Qué gas liberan las plantas durante la fotosíntesis?', 'oxígeno', 'dióxido de carbono', 'nitrógeno', 'hidrógeno'),
      p('¿Dónde se fabrican las proteínas?', 'en los ribosomas', 'en los lisosomas', 'en las vacuolas', 'en la pared celular'),
      p('¿Cuál es la unidad básica de todos los seres vivos?', 'la célula', 'el átomo', 'el tejido', 'el órgano'),
      par('mitosis', 'meiosis'),
      par('célula animal', 'célula vegetal'),
      par('ósmosis', 'difusión'),
      par('cloroplasto', 'mitocondria'),
      par('virus', 'bacteria'),
      par('procariota', 'eucariota'),
      enc('Nombrá una parte de la célula', 'núcleo = 30', 'mitocondria = 22', 'membrana / membrana plasmática = 18', 'citoplasma = 12', 'ribosoma = 10', 'cloroplasto = 8'),
    ],
  },
];
